// answers.js
// The curated list of possible SECRET words for BLINDLE, grouped by
// word length (4 through 20 letters). Every word here is a real,
// recognizable English word - and deliberately NOT a word that's just
// another (shorter) word in this file with a lazy "s" tacked on (we
// use FOOD, not FOODS; MINERAL, not MINERALS; TELECOMMUNICATION, not
// TELECOMMUNICATIONS). Longer lengths naturally have fewer options -
// genuinely common 18-20 letter English words are rare - but every
// length has at least a couple of solid choices.
//
// This is separate from the guess dictionary (see dictionary.js), which
// is enormous (370,000+ words) and used only to check whether a viewer's
// comment is a real, guessable word.

// EXPANDED POOL (update 8): each length now holds several hundred everyday words
// (was ~20-80), so the same answers rarely repeat. Words are still common and
// recognizable - nothing obscure - and still skip lazy "+s" plurals of other
// entries. Lengths 15-20 stay small because very few everyday English words
// are that long.

export const ANSWER_WORDS = {
  4: [
    "able", "acid", "aged", "arch", "area", "army",
    "atom", "aunt", "baby", "back", "bake", "ball",
    "band", "bank", "barn", "base", "bath", "beam",
    "bean", "bear", "beat", "beef", "beer", "bell",
    "belt", "bike", "bill", "bird", "bite", "blow",
    "blue", "boat", "body", "bold", "bolt", "bond",
    "bone", "book", "boot", "boss", "bowl", "bulb",
    "bull", "burn", "bush", "busy", "cafe", "cake",
    "calf", "call", "calm", "camp", "cape", "care",
    "cart", "case", "cash", "cast", "cave", "cell",
    "chat", "chef", "chin", "chip", "city", "clam",
    "clay", "clip", "club", "clue", "coal", "coat",
    "code", "coin", "cold", "colt", "cone", "cook",
    "cool", "cord", "core", "corn", "cost", "crab",
    "crew", "crop", "crow", "cube", "curl", "cute",
    "dare", "dark", "dart", "dash", "data", "dawn",
    "deal", "dear", "debt", "deck", "deep", "deer",
    "desk", "dial", "dice", "diet", "dime", "dine",
    "dirt", "dish", "dive", "dock", "dome", "door",
    "dose", "dove", "down", "draw", "drip", "drop",
    "drum", "duck", "dusk", "dust", "duty", "earn",
    "ease", "east", "easy", "edge", "envy", "epic",
    "even", "exam", "exit", "face", "fact", "fade",
    "fail", "fair", "fake", "fall", "fame", "farm",
    "fast", "fate", "fawn", "feed", "feel", "fern",
    "file", "fill", "film", "find", "fine", "fire",
    "firm", "fish", "flag", "flap", "flat", "flea",
    "flip", "flow", "foal", "foam", "fold", "folk",
    "fond", "font", "food", "fool", "foot", "fork",
    "form", "fort", "four", "free", "frog", "fuel",
    "full", "fund", "fuse", "gain", "gale", "game",
    "gate", "gear", "gene", "gift", "girl", "give",
    "glad", "glow", "glue", "goal", "goat", "gold",
    "gong", "gown", "grab", "gray", "grid", "grin",
    "grip", "grow", "gulf", "gust", "hail", "hair",
    "half", "hall", "halt", "hand", "hard", "harm",
    "harp", "haul", "hawk", "heal", "heap", "hear",
    "heat", "heel", "help", "herb", "hero", "hide",
    "high", "hike", "hill", "hint", "hire", "hold",
    "hole", "holy", "home", "hood", "hook", "hope",
    "horn", "host", "hour", "huge", "hunt", "hurt",
    "icon", "idea", "inch", "iron", "isle", "item",
    "jade", "jail", "jazz", "jeep", "joke", "jolt",
    "jump", "jury", "keen", "keep", "kick", "kind",
    "king", "kiss", "kite", "knee", "knot", "lace",
    "lack", "lady", "lake", "lamb", "lamp", "land",
    "lane", "lark", "last", "late", "lava", "lawn",
    "lazy", "lead", "leaf", "leap", "lend", "lens",
    "life", "lift", "like", "lily", "lime", "line",
    "link", "lion", "list", "live", "load", "loaf",
    "loan", "lock", "loft", "long", "loop", "lord",
    "lost", "loud", "love", "luck", "lump", "lung",
    "lush", "lynx", "maid", "mail", "main", "make",
    "mall", "mane", "many", "mark", "mask", "mast",
    "mate", "maze", "meal", "mean", "meat", "melt",
    "menu", "mess", "mild", "mile", "milk", "mind",
    "mine", "mint", "mist", "moat", "mode", "mole",
    "monk", "mood", "moon", "moss", "most", "moth",
    "move", "much", "mule", "nail", "name", "navy",
    "neat", "neck", "nest", "news", "nice", "nine",
    "node", "noon", "nose", "note", "oath", "omen",
    "once", "only", "open", "oval", "oven", "pace",
    "pack", "page", "pail", "pain", "pair", "palm",
    "park", "part", "pass", "past", "path", "peak",
    "pear", "peel", "peer", "pest", "pick", "pier",
    "pile", "pill", "pine", "pink", "pipe", "plan",
    "play", "plot", "plug", "plum", "poem", "poet",
    "pole", "polo", "pond", "pony", "pool", "poor",
    "pork", "port", "pose", "post", "pour", "pray",
    "prey", "pull", "puma", "pump", "pure", "push",
    "quiz", "race", "rack", "raft", "rage", "rail",
    "rain", "ramp", "rank", "rare", "rash", "rate",
    "read", "real", "reed", "reef", "rely", "rent",
    "rest", "rice", "rich", "ride", "ring", "rink",
    "riot", "rise", "risk", "road", "roar", "robe",
    "rock", "role", "roof", "room", "root", "rope",
    "rose", "ruby", "rude", "rule", "rush", "rust",
    "sack", "safe", "sage", "sail", "sake", "salt",
    "sand", "sane", "scan", "scar", "seal", "seam",
    "seat", "seed", "self", "sell", "send", "shed",
    "shin", "ship", "shoe", "shop", "show", "shut",
    "sick", "side", "sift", "sign", "silk", "sing",
    "sink", "site", "size", "skip", "slam", "slap",
    "sled", "slim", "slip", "slow", "slug", "snap",
    "snow", "soap", "soar", "sock", "soft", "soil",
    "sold", "sole", "some", "song", "soon", "sore",
    "sort", "soul", "soup", "sour", "span", "spin",
    "spot", "spur", "stab", "star", "stay", "stem",
    "step", "stew", "stir", "stop", "stub", "such",
    "suit", "sure", "surf", "swan", "swap", "sway",
    "swim", "tale", "talk", "tall", "tank", "tape",
    "task", "taxi", "teal", "team", "tear", "tell",
    "tend", "tent", "term", "test", "text", "thaw",
    "then", "thin", "tide", "tidy", "tile", "till",
    "time", "tiny", "tire", "toad", "toil", "told",
    "toll", "tomb", "tone", "tool", "tour", "town",
    "trap", "tray", "tree", "trim", "trip", "trot",
    "true", "tube", "tuck", "tuna", "tune", "turn",
    "twin", "type", "ugly", "unit", "upon", "urge",
    "used", "vain", "vase", "vast", "veil", "verb",
    "very", "vest", "view", "vine", "visa", "void",
    "vote", "wade", "wage", "wait", "wake", "walk",
    "wall", "want", "warm", "warn", "wash", "wasp",
    "wave", "wavy", "weak", "wear", "weed", "week",
    "well", "west", "wide", "wife", "wild", "will",
    "wind", "wine", "wing", "wink", "wipe", "wire",
    "wise", "wish", "wolf", "wood", "wool", "word",
    "work", "worm", "wrap", "yard", "yarn", "year",
    "yell", "yoga", "zero", "zone", "zoom",
  ],
  5: [
    "abbey", "actor", "adult", "agent", "alarm", "album",
    "alert", "alien", "alley", "amber", "angel", "anger",
    "angle", "ankle", "apple", "apron", "arena", "aroma",
    "arrow", "aside", "atlas", "attic", "audio", "award",
    "baker", "banjo", "barge", "baron", "basil", "beach",
    "beard", "beast", "bench", "berry", "bingo", "birch",
    "black", "blade", "blame", "blank", "blast", "blaze",
    "bloom", "blush", "board", "boast", "bonus", "boost",
    "booth", "brain", "brake", "brand", "brave", "bread",
    "brick", "bride", "brief", "bring", "brook", "broom",
    "brown", "brush", "buddy", "build", "bunny", "burst",
    "cabin", "cable", "camel", "canal", "candy", "canoe",
    "carol", "carry", "catch", "cause", "cedar", "chain",
    "chair", "chalk", "chaos", "charm", "chart", "chase",
    "cheap", "check", "cheek", "cheer", "chess", "chest",
    "chick", "chief", "child", "chill", "chime", "chunk",
    "cider", "cigar", "civic", "claim", "clash", "class",
    "clean", "clerk", "click", "cliff", "climb", "cloak",
    "clock", "close", "cloth", "cloud", "clown", "coach",
    "coast", "cobra", "cocoa", "comet", "comic", "coral",
    "couch", "cough", "count", "court", "cover", "crack",
    "craft", "crane", "crash", "crawl", "crazy", "cream",
    "creek", "crisp", "cross", "crowd", "crown", "cruel",
    "crush", "curry", "curve", "daily", "daisy", "dance",
    "delta", "dense", "depth", "diary", "diner", "dizzy",
    "dodge", "donor", "doubt", "dough", "dozen", "draft",
    "drain", "drama", "dream", "dress", "drift", "drill",
    "drink", "drive", "eager", "eagle", "early", "earth",
    "easel", "elbow", "elder", "elite", "empty", "enjoy",
    "enter", "entry", "equal", "error", "event", "extra",
    "fable", "fairy", "faith", "false", "fancy", "feast",
    "fence", "ferry", "fever", "fiber", "field", "fifth",
    "fifty", "fight", "final", "first", "flair", "flame",
    "flash", "fleet", "flesh", "flock", "flood", "floor",
    "flour", "fluid", "flute", "focus", "force", "forge",
    "forty", "forum", "frame", "fresh", "frost", "fruit",
    "fudge", "funny", "gauge", "ghost", "giant", "given",
    "glass", "glide", "globe", "gloom", "glory", "glove",
    "goose", "grace", "grade", "grain", "grand", "grant",
    "grape", "graph", "grass", "gravy", "great", "green",
    "greet", "grill", "groom", "group", "grove", "guard",
    "guess", "guest", "guide", "habit", "happy", "harsh",
    "haste", "hasty", "hatch", "haunt", "heart", "heavy",
    "hedge", "hello", "hence", "hiker", "hippo", "hobby",
    "holly", "honey", "honor", "horse", "hotel", "house",
    "human", "humor", "hurry", "hyena", "icing", "ideal",
    "igloo", "image", "inbox", "index", "inner", "input",
    "intro", "irony", "issue", "ivory", "jelly", "jewel",
    "joker", "jolly", "judge", "juice", "juicy", "karma",
    "kayak", "kebab", "kneel", "knife", "knock", "koala",
    "label", "lance", "large", "laser", "latch", "later",
    "laugh", "layer", "learn", "lease", "leave", "legal",
    "lemon", "lemur", "level", "lever", "light", "limit",
    "linen", "liner", "lobby", "local", "lodge", "logic",
    "loose", "lover", "lower", "loyal", "lucky", "lunar",
    "lunch", "lurch", "madam", "magic", "major", "mango",
    "maple", "march", "marsh", "mason", "match", "mayor",
    "medal", "melon", "mercy", "merit", "metal", "meter",
    "might", "minor", "mixer", "model", "moist", "money",
    "month", "moral", "motor", "motto", "mount", "mouse",
    "mouth", "movie", "muddy", "music", "naive", "nanny",
    "nasty", "naval", "nerve", "never", "newly", "niche",
    "night", "ninja", "noble", "noise", "nomad", "north",
    "novel", "nurse", "nutty", "oasis", "ocean", "offer",
    "often", "olive", "onion", "opera", "opine", "orbit",
    "other", "otter", "outer", "owner", "ozone", "paint",
    "panda", "panel", "panic", "pants", "paper", "party",
    "pasta", "patch", "pause", "peace", "peach", "pearl",
    "pedal", "penny", "perch", "phase", "phone", "photo",
    "piano", "pilot", "pinch", "pitch", "pizza", "place",
    "plain", "plane", "plant", "plate", "plaza", "plead",
    "pluck", "plush", "poach", "point", "poker", "polar",
    "polka", "porch", "pouch", "pound", "power", "press",
    "price", "pride", "prime", "print", "prize", "proof",
    "proud", "prove", "pulse", "punch", "pupil", "puppy",
    "purse", "quack", "quake", "quart", "queen", "queue",
    "quick", "quiet", "quilt", "quote", "radar", "radio",
    "raise", "rally", "ranch", "range", "rapid", "ratio",
    "raven", "razor", "reach", "react", "ready", "realm",
    "rebel", "refer", "reign", "relax", "relay", "renew",
    "reply", "rider", "ridge", "rifle", "right", "rigid",
    "rinse", "risky", "rival", "river", "robin", "robot",
    "rocky", "rogue", "round", "route", "royal", "rugby",
    "ruler", "rural", "sadly", "saint", "salad", "salon",
    "sandy", "sauce", "sauna", "scale", "scarf", "scene",
    "scent", "scoop", "scope", "score", "scout", "screw",
    "scrub", "seven", "shade", "shaft", "shake", "shape",
    "share", "shark", "sharp", "sheep", "sheet", "shelf",
    "shell", "shine", "shiny", "shirt", "shock", "shore",
    "short", "shout", "shrub", "siege", "sight", "silky",
    "silly", "since", "sixth", "skate", "skill", "skirt",
    "skull", "slate", "sleep", "slept", "slice", "slide",
    "slope", "small", "smart", "smell", "smile", "smoke",
    "snack", "snail", "snake", "sneak", "solar", "solid",
    "solve", "sorry", "sound", "south", "space", "spare",
    "spark", "speak", "speed", "spell", "spend", "spice",
    "spicy", "spike", "spine", "spoon", "sport", "spray",
    "squad", "stack", "staff", "stage", "stain", "stair",
    "stake", "stamp", "stand", "stare", "start", "state",
    "steak", "steam", "steel", "steep", "steer", "stick",
    "stiff", "still", "sting", "stock", "stone", "stood",
    "stool", "store", "storm", "story", "stove", "straw",
    "strip", "stuck", "study", "stuff", "style", "sugar",
    "suite", "sunny", "super", "surge", "swamp", "swarm",
    "swear", "sweat", "sweep", "sweet", "swift", "swing",
    "sword", "table", "taste", "teach", "teddy", "teeth",
    "tempo", "tenor", "tense", "tenth", "thank", "theme",
    "thick", "thief", "thing", "think", "third", "thorn",
    "three", "throw", "thumb", "tidal", "tiger", "tight",
    "timer", "tired", "title", "toast", "today", "tonic",
    "tooth", "topic", "torch", "total", "touch", "tough",
    "towel", "tower", "toxic", "trace", "track", "trade",
    "trail", "train", "trait", "tramp", "trash", "treat",
    "trend", "trial", "tribe", "trick", "troop", "trout",
    "truck", "truly", "trunk", "trust", "truth", "tulip",
    "tunic", "turbo", "tutor", "twice", "twist", "ultra",
    "uncle", "under", "union", "unite", "unity", "upper",
    "upset", "urban", "usage", "usual", "utter", "valid",
    "value", "valve", "vapor", "vault", "venue", "verse",
    "video", "vigor", "villa", "vinyl", "viola", "viral",
    "virus", "visit", "vital", "vivid", "vocal", "voice",
    "voter", "wafer", "wagon", "waist", "waltz", "waste",
    "watch", "water", "weary", "weave", "wedge", "weigh",
    "weird", "whale", "wheat", "wheel", "where", "while",
    "whirl", "white", "whole", "whose", "widow", "width",
    "wield", "windy", "witch", "woman", "world", "worry",
    "worth", "would", "wound", "wrist", "wrong", "yacht",
    "yield", "young", "youth", "zebra", "zesty",
  ],
  6: [
    "abroad", "accent", "access", "accuse", "acting", "action",
    "active", "actual", "advice", "affair", "afford", "agency",
    "agenda", "almond", "almost", "amount", "anchor", "animal",
    "annual", "answer", "anyone", "appeal", "appear", "arctic",
    "around", "arrive", "artist", "aspect", "assist", "attack",
    "attend", "author", "autumn", "avenue", "badger", "bakery",
    "ballet", "banner", "barber", "barrel", "basket", "battle",
    "beacon", "beauty", "become", "before", "behind", "belief",
    "belong", "beside", "better", "beyond", "bishop", "bitter",
    "blouse", "border", "borrow", "bottle", "bottom", "bounce",
    "branch", "breeze", "bridge", "bright", "broken", "bronze",
    "bubble", "bucket", "budget", "buffet", "bundle", "burden",
    "bureau", "butler", "button", "cactus", "camera", "campus",
    "candle", "canyon", "carbon", "career", "carpet", "casino",
    "castle", "cattle", "caught", "center", "chance", "change",
    "chapel", "charge", "cheese", "cherry", "chilly", "choice",
    "choose", "chorus", "circle", "circus", "clever", "client",
    "clinic", "closet", "clover", "coffee", "column", "comedy",
    "common", "copper", "corner", "cotton", "county", "couple",
    "course", "cousin", "cradle", "crayon", "create", "credit",
    "cruise", "custom", "dancer", "danger", "dealer", "debate",
    "decade", "decent", "decide", "deeper", "defend", "define",
    "degree", "demand", "dental", "desert", "design", "desire",
    "detail", "detect", "device", "dinner", "direct", "doctor",
    "dollar", "donkey", "doodle", "double", "dragon", "drawer",
    "dreamy", "driver", "during", "easily", "eleven", "emblem",
    "emerge", "empire", "enable", "ending", "energy", "engage",
    "engine", "enough", "ensure", "entire", "escape", "estate",
    "evolve", "excuse", "exotic", "expand", "expert", "export",
    "extend", "fabric", "factor", "fairly", "falcon", "fallen",
    "family", "famous", "farmer", "fasten", "father", "fellow",
    "fiddle", "figure", "filter", "finger", "finish", "fiscal",
    "flavor", "flight", "flower", "flying", "follow", "forbid",
    "forest", "forget", "formal", "former", "fossil", "fourth",
    "freeze", "friend", "frozen", "fruity", "future", "gadget",
    "galaxy", "gallon", "gamble", "garage", "garden", "garlic",
    "gentle", "ginger", "glance", "global", "gloomy", "goblet",
    "golden", "gospel", "gossip", "govern", "grease", "groove",
    "ground", "growth", "guilty", "guitar", "hammer", "handle",
    "happen", "harbor", "hardly", "hazard", "health", "heater",
    "height", "helmet", "hermit", "hidden", "hockey", "honest",
    "hungry", "hunter", "hybrid", "icicle", "ignore", "impact",
    "indoor", "infant", "inform", "injury", "insect", "inside",
    "invent", "invite", "island", "jacket", "jersey", "jigsaw",
    "jungle", "junior", "kennel", "kettle", "kitten", "ladder",
    "lagoon", "lately", "laurel", "lawyer", "leader", "league",
    "legend", "lesson", "letter", "lizard", "lonely", "lovely",
    "lumber", "luxury", "magnet", "mammal", "manage", "manner",
    "marble", "margin", "marine", "market", "master", "matter",
    "meadow", "medium", "member", "memory", "mental", "merely",
    "method", "middle", "minute", "mirror", "modern", "modest",
    "moment", "monkey", "mother", "motion", "muffin", "murmur",
    "muscle", "museum", "mutual", "myself", "narrow", "nation",
    "nature", "nearby", "needle", "nephew", "nickel", "nobody",
    "normal", "notice", "notion", "number", "object", "obtain",
    "office", "online", "opener", "oppose", "option", "orange",
    "orchid", "origin", "outfit", "outlet", "output", "oxygen",
    "paddle", "palace", "parade", "parcel", "parent", "parrot",
    "patrol", "pencil", "people", "pepper", "period", "permit",
    "person", "pickle", "picnic", "pillow", "planet", "player",
    "please", "pledge", "pocket", "poetry", "police", "polite",
    "potato", "powder", "prefer", "pretty", "prince", "prison",
    "profit", "prompt", "proper", "puppet", "purple", "puzzle",
    "quartz", "quiver", "rabbit", "racing", "radish", "rarely",
    "rather", "reader", "really", "reason", "recall", "recipe",
    "record", "reform", "refuse", "region", "reject", "relate",
    "relief", "remain", "remedy", "remind", "remote", "remove",
    "repair", "repeat", "report", "rescue", "resort", "result",
    "retire", "return", "reveal", "review", "reward", "rhythm",
    "ribbon", "riddle", "rocket", "rubber", "ruling", "runner",
    "saddle", "safety", "salmon", "sample", "sandal", "scarce",
    "scheme", "school", "scream", "screen", "script", "search",
    "season", "second", "secret", "sector", "secure", "select",
    "sender", "senior", "series", "server", "settle", "shadow",
    "shield", "shower", "signal", "silent", "silver", "simple",
    "singer", "sister", "sketch", "slogan", "smooth", "snappy",
    "soccer", "social", "socket", "soften", "solemn", "spider",
    "spirit", "splash", "spring", "square", "squash", "stable",
    "statue", "steady", "stereo", "stitch", "stormy", "stream",
    "street", "stress", "strict", "strike", "string", "stripe",
    "strong", "studio", "submit", "sudden", "suffer", "summer",
    "sunset", "supper", "supply", "surely", "survey", "switch",
    "symbol", "system", "tablet", "tackle", "talent", "target",
    "tattoo", "temple", "tender", "tennis", "theory", "thirty",
    "though", "thread", "thrill", "throat", "ticket", "tickle",
    "timber", "tissue", "tomato", "tongue", "toward", "travel",
    "treaty", "tribal", "trophy", "tunnel", "turkey", "turtle",
    "twelve", "twenty", "unable", "unique", "unless", "unlike",
    "update", "upload", "urgent", "useful", "valley", "vanish",
    "velvet", "vendor", "vessel", "victim", "violet", "visual",
    "volume", "voyage", "waffle", "walnut", "wander", "warden",
    "warmth", "wealth", "weapon", "weasel", "weekly", "weight",
    "window", "winter", "wisdom", "wizard", "wonder", "wooden",
    "worker", "worthy", "yellow", "yogurt", "zenith", "zipper",
    "zodiac",
  ],
  7: [
    "ability", "academy", "account", "achieve", "acrobat", "address",
    "advance", "airline", "airport", "alcohol", "amazing", "ancient",
    "anxiety", "applaud", "apricot", "archive", "arrange", "arrival",
    "article", "artisan", "athlete", "attempt", "attract", "auction",
    "average", "balance", "balloon", "bandage", "banquet", "bargain",
    "barrier", "bathtub", "battery", "bearing", "bedroom", "believe",
    "benefit", "biscuit", "blanket", "blossom", "bonfire", "bracket",
    "brother", "cabbage", "cabinet", "capital", "captain", "capture",
    "caravan", "caution", "ceiling", "central", "century", "chamber",
    "channel", "chapter", "charity", "charter", "chicken", "chimney",
    "chronic", "circuit", "citizen", "classic", "climate", "cluster",
    "coconut", "collage", "college", "command", "comment", "compass",
    "complex", "concert", "conduct", "connect", "consent", "contact",
    "content", "contest", "context", "control", "costume", "cottage",
    "council", "counter", "country", "courage", "crystal", "culture",
    "curious", "current", "custard", "cutting", "dancing", "decline",
    "default", "defense", "delight", "deliver", "density", "deposit",
    "desktop", "destiny", "diamond", "digital", "dignity", "dilemma",
    "diploma", "dolphin", "drawing", "dresser", "drizzle", "dungeon",
    "eastern", "economy", "edition", "elegant", "element", "embrace",
    "emotion", "emperor", "enclose", "endless", "english", "enhance",
    "episode", "essence", "evening", "exactly", "examine", "example",
    "excited", "exhaust", "exhibit", "explain", "explore", "express",
    "extreme", "factory", "failure", "fantasy", "fashion", "feather",
    "feature", "fiction", "fighter", "finally", "finance", "fishing",
    "fitness", "flutter", "forever", "forgive", "formula", "fortune",
    "forward", "fragile", "freedom", "freight", "gallery", "garment",
    "general", "gesture", "giraffe", "glacier", "glimpse", "glitter",
    "gravity", "grocery", "growing", "habitat", "halfway", "hammock",
    "handful", "harmony", "harvest", "healthy", "hearing", "helpful",
    "herself", "history", "holiday", "hostile", "hundred", "hunting",
    "husband", "iceberg", "illness", "imagine", "impress", "improve",
    "include", "inquire", "insight", "inspire", "install", "instant",
    "intense", "involve", "jackpot", "jasmine", "jealous", "jewelry",
    "journal", "journey", "juggler", "justice", "kingdom", "kitchen",
    "knowing", "knuckle", "lantern", "lasting", "laundry", "lecture",
    "leopard", "lettuce", "liberty", "library", "license", "lighter",
    "limited", "lobster", "lottery", "machine", "magical", "mailbox",
    "mammoth", "mansion", "massive", "meaning", "measure", "medical",
    "meeting", "mention", "message", "mineral", "minimum", "miracle",
    "mission", "mixture", "monitor", "monster", "monthly", "morning",
    "mustard", "mystery", "natural", "nearest", "neither", "nervous",
    "network", "neutral", "notable", "nothing", "nuclear", "nursery",
    "obvious", "octopus", "officer", "opening", "opinion", "orchard",
    "organic", "outdoor", "outlook", "outside", "overall", "package",
    "painter", "palette", "pancake", "panther", "parking", "partner",
    "passage", "passion", "pasture", "pattern", "payment", "peasant",
    "pelican", "penalty", "pension", "perfect", "perfume", "phoenix",
    "picture", "pioneer", "planner", "plastic", "playful", "popcorn",
    "portion", "possess", "postage", "poverty", "predict", "premium",
    "present", "pretend", "prevent", "primary", "printer", "privacy",
    "problem", "process", "produce", "product", "profile", "program",
    "project", "promise", "protect", "protein", "provide", "pudding",
    "pumpkin", "purpose", "pursuit", "quality", "quantum", "quarter",
    "quartet", "quickly", "rainbow", "reached", "reading", "reality",
    "receipt", "recover", "recycle", "reflect", "refresh", "regular",
    "related", "release", "relieve", "removal", "replace", "reptile",
    "request", "require", "reserve", "resolve", "respect", "respond",
    "restore", "retreat", "revenue", "reverse", "rhubarb", "rooster",
    "routine", "running", "sadness", "sailing", "sandbox", "satisfy",
    "scholar", "science", "scooter", "scratch", "seagull", "section",
    "seeking", "senator", "serious", "service", "session", "setting",
    "seventh", "shallow", "shampoo", "sharing", "shelter", "sheriff",
    "shining", "shorter", "shuttle", "silence", "similar", "singing",
    "sixteen", "slender", "smaller", "smiling", "society", "soldier",
    "solving", "someone", "sparrow", "special", "sponsor", "stadium",
    "station", "staying", "steamer", "sticker", "stomach", "storage",
    "strange", "stretch", "student", "subject", "success", "suggest",
    "summary", "sunrise", "support", "suppose", "supreme", "surface",
    "surgeon", "surplus", "survive", "suspect", "sustain", "swimmer",
    "symptom", "teacher", "tension", "terrace", "texture", "theater",
    "therapy", "thicken", "thirsty", "thought", "thunder", "topping",
    "tornado", "tourist", "trading", "traffic", "tragedy", "trailer",
    "trainer", "transit", "trapeze", "treason", "trouble", "trumpet",
    "typhoon", "unicorn", "uniform", "unusual", "upgrade", "useless",
    "vacancy", "vaccine", "vampire", "variety", "vehicle", "venture",
    "verdict", "version", "veteran", "village", "vintage", "violent",
    "virtual", "visible", "visitor", "vitamin", "volcano", "voucher",
    "walking", "warning", "washing", "wealthy", "weather", "wedding",
    "weekend", "welcome", "western", "whisper", "wildcat", "willing",
    "winning", "wishing", "without", "witness", "working", "worried",
    "writing", "written",
  ],
  8: [
    "absolute", "abstract", "academic", "accident", "accurate", "activity",
    "actually", "addition", "adequate", "airplane", "alphabet", "aluminum",
    "ambition", "ancestor", "announce", "anywhere", "apparent", "appetite",
    "applause", "approach", "approval", "aquarium", "argument", "armchair",
    "artistic", "assemble", "assorted", "athletic", "attitude", "audience",
    "backbone", "backpack", "bacteria", "baseball", "bathroom", "birthday",
    "blizzard", "bookcase", "bookmark", "boundary", "broccoli", "building",
    "bulletin", "business", "calendar", "campaign", "capacity", "cardinal",
    "careless", "carnival", "carriage", "category", "cautious", "champion",
    "chemical", "children", "chipmunk", "circular", "civilian", "classify",
    "clearing", "climbing", "clothing", "collapse", "colorful", "combined",
    "comedian", "commerce", "complain", "complete", "computer", "conclude",
    "concrete", "conflict", "confused", "congress", "consider", "constant",
    "contract", "contrast", "convince", "creation", "creative", "creature",
    "criminal", "critical", "crossing", "cucumber", "customer", "database",
    "daughter", "decision", "decorate", "dedicate", "defender", "definite",
    "delicate", "delivery", "describe", "designer", "detailed", "detector",
    "dialogue", "directly", "disaster", "discount", "discover", "distance",
    "distinct", "district", "dividend", "doorbell", "dramatic", "dressing",
    "driveway", "duration", "dynamite", "election", "elegance", "elephant",
    "elevator", "emission", "emphasis", "employee", "employer", "endeavor",
    "engineer", "enormous", "entrance", "envelope", "equation", "eruption",
    "escalate", "estimate", "evaluate", "eventual", "everyday", "evidence",
    "exchange", "exciting", "exercise", "existing", "expected", "explorer",
    "exposure", "extended", "external", "fabulous", "facility", "familiar",
    "farewell", "farmland", "favorite", "festival", "fighting", "figurine",
    "finalist", "firewood", "firework", "fishbowl", "flagship", "flamingo",
    "flexible", "floating", "flooding", "foothill", "footstep", "forecast",
    "forklift", "fortress", "fraction", "fragment", "frequent", "friendly",
    "frontier", "frosting", "function", "gasoline", "generous", "gigantic",
    "glorious", "gorgeous", "graceful", "graduate", "grateful", "greeting",
    "handsome", "hardware", "harmless", "headache", "headline", "heavenly",
    "hedgehog", "hesitate", "highland", "homework", "honestly", "hospital",
    "identity", "illusion", "incident", "industry", "infinite", "informal",
    "innocent", "instance", "interest", "interior", "internal", "interval",
    "invasion", "isolated", "judgment", "junction", "keyboard", "kindness",
    "knapsack", "landlord", "landmark", "language", "lavender", "lifetime",
    "lighting", "likewise", "listener", "literary", "location", "lollipop",
    "lonesome", "magazine", "magnetic", "majority", "marigold", "material",
    "maternal", "meantime", "medicine", "membrane", "memorial", "merchant",
    "midnight", "military", "minister", "minority", "mistaken", "moderate",
    "molecule", "momentum", "moonbeam", "mosquito", "mountain", "movement",
    "multiple", "musician", "mystical", "narrator", "national", "navigate",
    "negative", "neighbor", "nonsense", "northern", "notebook", "novelist",
    "nutrient", "obstacle", "occasion", "offering", "official", "operator",
    "opposite", "optional", "ordinary", "organize", "original", "outlined",
    "overcome", "overhead", "overlook", "painting", "paradise", "parallel",
    "particle", "passport", "patience", "pavement", "peaceful", "pedestal",
    "personal", "physical", "pinwheel", "pipeline", "plankton", "planting",
    "platform", "pleasant", "pleasure", "plumbing", "polished", "portable",
    "position", "positive", "possible", "postcard", "powerful", "practice",
    "precious", "preserve", "pressure", "previous", "princess", "printing",
    "priority", "prisoner", "progress", "promised", "properly", "property",
    "proposal", "prospect", "provider", "province", "purchase", "quantity",
    "question", "radiator", "rational", "reaction", "receiver", "recently",
    "reckless", "recorder", "recovery", "regional", "register", "relation",
    "relative", "relaxing", "reliable", "religion", "remember", "reminder",
    "repeated", "reporter", "republic", "required", "research", "reserved",
    "resident", "resource", "response", "restless", "restroom", "retailer",
    "revision", "richness", "ringtone", "riverbed", "romantic", "roommate",
    "rotation", "sandwich", "sapphire", "scenario", "schedule", "sculptor",
    "seashell", "seashore", "seatbelt", "selected", "selfless", "semester",
    "sensible", "sentence", "sequence", "shipment", "shopping", "shoulder",
    "showcase", "sidekick", "sidewalk", "silently", "simplify", "skeleton",
    "skillful", "slightly", "slippery", "snowfall", "software", "solution",
    "somewhat", "southern", "souvenir", "specific", "specimen", "spectrum",
    "spelling", "spinning", "splendid", "spotless", "standard", "standing",
    "starfish", "starting", "steadily", "sticking", "stimulus", "stingray",
    "stirring", "straight", "strategy", "strength", "stressed", "striking",
    "struggle", "stunning", "sunlight", "sunshine", "surprise", "surround",
    "survival", "suspense", "sweeping", "swimming", "symbolic", "sympathy",
    "symphony", "tabletop", "tactical", "tailored", "tangible", "tapestry",
    "teaching", "teammate", "teaspoon", "teenager", "telegram", "template",
    "terminal", "terrible", "terrific", "textbook", "thankful", "thorough",
    "thousand", "throwing", "timeless", "timeline", "tomorrow", "tortoise",
    "tracking", "training", "transfer", "traveler", "treasure", "triangle",
    "tricycle", "tropical", "truthful", "tutorial", "ultimate", "umbrella",
    "unbroken", "uncommon", "underway", "universe", "unlikely", "vacation",
    "valuable", "variable", "velocity", "vertical", "vineyard", "violence",
    "wardrobe", "wasteful", "watchful", "weighted", "whenever", "wildfire",
    "wildlife", "windmill", "wireless", "wishbone", "woodland", "workshop",
    "wrapping",
  ],
  9: [
    "abundance", "accepting", "accessory", "accordion", "adventure", "afternoon",
    "agreement", "alligator", "ambulance", "announcer", "apartment", "appetizer",
    "appliance", "architect", "artichoke", "assistant", "attendant", "authentic",
    "available", "bandwidth", "beginning", "billboard", "biography", "blackbird",
    "blueberry", "bookshelf", "boomerang", "boulevard", "breakfast", "broadcast",
    "butterfly", "calculate", "candidate", "cartwheel", "cathedral", "celebrate",
    "celebrity", "challenge", "character", "chocolate", "classroom", "clipboard",
    "collector", "commander", "community", "companion", "condition", "conductor",
    "confident", "connected", "container", "continent", "cooperate", "courtyard",
    "cranberry", "crocodile", "crossword", "customize", "dandelion", "decorated",
    "delicious", "democracy", "departure", "described", "direction", "directory",
    "discovery", "dragonfly", "education", "efficient", "elaborate", "emergency",
    "encounter", "encourage", "enjoyment", "equipment", "essential", "evergreen",
    "everybody", "excellent", "exception", "excursion", "executive", "exhausted",
    "expansion", "expensive", "explained", "explosion", "fairytale", "fantastic",
    "fireplace", "flashback", "following", "footprint", "formation", "fortunate",
    "framework", "furniture", "gardening", "generally", "generator", "gentleman",
    "geography", "graduated", "gratitude", "guarantee", "hairbrush", "happiness",
    "headphone", "hibernate", "hilarious", "hurricane", "imaginary", "important",
    "indicator", "influence", "inspector", "instantly", "intention", "interview",
    "invention", "inventory", "invisible", "jellyfish", "kilometer", "knowledge",
    "landscape", "lawnmower", "librarian", "lightning", "limestone", "lunchtime",
    "marketing", "marmalade", "mechanism", "memorable", "mentioned", "messenger",
    "microwave", "migration", "milkshake", "monastery", "narrative", "necessary",
    "newspaper", "nightmare", "northwest", "nostalgia", "nutrition", "observing",
    "obviously", "operation", "orchestra", "outspoken", "overboard", "overnight",
    "paragraph", "parameter", "passenger", "perfectly", "performer", "photocopy",
    "pineapple", "placement", "playhouse", "policeman", "porcupine", "portfolio",
    "potential", "practical", "precisely", "predicted", "president", "primarily",
    "principal", "principle", "printable", "privilege", "procedure", "professor",
    "promotion", "propeller", "protected", "provision", "publisher", "purchased",
    "quarterly", "quicksand", "reasoning", "recommend", "recording", "rectangle",
    "reference", "reflected", "regarding", "regularly", "remaining", "rendering",
    "repeating", "represent", "respected", "responded", "resulting", "retrieval",
    "reversing", "revolving", "rewarding", "satellite", "satisfied", "scarecrow",
    "scattered", "scientist", "secretary", "selection", "semicolon", "sensation",
    "separated", "shipwreck", "shortcake", "simulator", "situation", "slideshow",
    "snowboard", "snowflake", "snowstorm", "something", "sophomore", "southwest",
    "spacesuit", "spaghetti", "speedboat", "spotlight", "sprinkler", "staircase",
    "statement", "steamboat", "stretcher", "structure", "struggled", "subscribe",
    "substance", "suggested", "sunflower", "superhero", "surprised", "suspected",
    "sweetener", "tangerine", "technique", "telephone", "telescope", "temperate",
    "temporary", "territory", "therapist", "thickness", "thrilling", "throwback",
    "timetable", "tolerance", "touchdown", "transport", "traveling", "treatment",
    "turquoise", "typically", "underline", "undertake", "universal", "unlimited",
    "variation", "vegetable", "versatile", "vibration", "victorian", "viewpoint",
    "violation", "volunteer", "warehouse", "waterfall", "welcoming", "wellbeing",
    "whirlpool", "wholesome", "wonderful", "workplace", "xylophone", "yesterday",
    "zookeeper",
  ],
  10: [
    "absolutely", "accidental", "accomplish", "accountant", "adaptation", "adventurer",
    "affordable", "aggressive", "ambassador", "announcing", "appearance", "appreciate",
    "arithmetic", "artificial", "assignment", "atmosphere", "attendance", "attractive",
    "automobile", "background", "barbershop", "basketball", "battleship", "beforehand",
    "birthplace", "blackboard", "calculator", "cappuccino", "celebrated", "centimeter",
    "challenged", "charitable", "chimpanzee", "collection", "commercial", "comparison",
    "compassion", "competitor", "completely", "complicate", "conception", "concerning",
    "conclusion", "conference", "connection", "conscience", "consistent", "continuous",
    "contribute", "controlled", "convenient", "conversion", "coordinate", "correction",
    "courageous", "courthouse", "crossroads", "dedication", "definitely", "delightful",
    "demolition", "dependable", "determined", "dictionary", "difference", "difficulty",
    "discipline", "discovered", "discussion", "dishwasher", "disturbing", "downstairs",
    "drawbridge", "earthquake", "economical", "efficiency", "electrical", "electronic",
    "elementary", "employment", "enormously", "enterprise", "enthusiasm", "evaluation",
    "everything", "everywhere", "excellence", "excitement", "exhibition", "expedition",
    "experience", "experiment", "explaining", "expressive", "eyewitness", "federation",
    "fellowship", "fertilizer", "fiberglass", "fingernail", "flashlight", "flattering",
    "fluttering", "footprints", "formidable", "foundation", "freshwater", "friendship",
    "frightened", "fulfilling", "generation", "generosity", "goalkeeper", "government",
    "graduation", "grandchild", "grandstand", "gratefully", "greenhouse", "groundwork",
    "guaranteed", "gymnastics", "handsomely", "healthcare", "helicopter", "hesitation",
    "historical", "homecoming", "hopelessly", "horsepower", "hospitable", "illuminate",
    "illustrate", "importance", "indication", "individual", "industrial", "inevitable",
    "ingredient", "innovation", "instructor", "invitation", "journalism", "journalist",
    "laboratory", "lighthouse", "literature", "lumberjack", "mainstream", "mastermind",
    "medication", "membership", "microphone", "microscope", "millennium", "miraculous",
    "monitoring", "motherhood", "motivation", "motorcycle", "mysterious", "nationwide",
    "navigation", "neighborly", "networking", "neutrality", "nomination", "nonfiction",
    "noteworthy", "noticeable", "nourishing", "obligation", "occasional", "occupation",
    "officially", "optimistic", "ordinarily", "originally", "overweight", "paddleboat",
    "paintbrush", "parliament", "particular", "passageway", "passionate", "peacefully",
    "peacemaker", "pedestrian", "peppermint", "percentage", "perception", "permission",
    "personable", "persuasive", "pharmacist", "philosophy", "photograph", "pickpocket",
    "pilgrimage", "plantation", "playground", "population", "positively", "prevailing",
    "prevention", "previously", "prioritize", "production", "profession", "proficient",
    "prohibited", "proportion", "prosperity", "protection", "provincial", "questioner",
    "rainforest", "reasonable", "reflection", "regulation", "relaxation", "relentless",
    "renovation", "repertoire", "repetition", "reputation", "resistance", "resolution",
    "restaurant", "restricted", "revelation", "revolution", "roundabout", "sandcastle",
    "scoreboard", "separation", "silverware", "simplicity", "skateboard", "snowmobile",
    "soundtrack", "specialist", "springtime", "starvation", "stereotype", "strawberry",
    "strengthen", "stretching", "substitute", "succeeding", "sufficient", "suggestion",
    "supervisor", "surprising", "surrounded", "sweatshirt", "sweetheart", "tambourine",
    "technician", "technology", "television", "terrifying", "themselves", "thermostat",
    "thoughtful", "timekeeper", "toothbrush", "toothpaste", "tournament", "transition",
    "tremendous", "turnaround", "turtleneck", "typewriter", "undergoing", "understand",
    "unforeseen", "university", "vegetarian", "vocabulary", "volleyball", "watermelon",
    "wilderness", "windshield", "wonderland", "woodpecker", "xenophobia", "yesteryear",
  ],
  11: [
    "adventurous", "afterschool", "anniversary", "arrangement", "broadcaster", "calculation",
    "candlestick", "celebration", "circulation", "combination", "commentator", "communicate",
    "competition", "consequence", "continental", "cooperation", "corporation", "correlation",
    "description", "distinction", "documentary", "electricity", "elimination", "encouraging",
    "engineering", "entertained", "environment", "examination", "explanation", "exploration",
    "fascinating", "fingerprint", "firefighter", "flourishing", "forecasting", "frightening",
    "grandparent", "handwriting", "housekeeper", "hummingbird", "illustrated", "imagination",
    "improvement", "independent", "information", "inheritance", "inspiration", "institution",
    "instruction", "integration", "intelligent", "interesting", "interrupted", "involvement",
    "landscaping", "legislation", "lightweight", "magnificent", "maintenance", "manufacture",
    "masterpiece", "mathematics", "measurement", "microscopic", "mischievous", "mountaineer",
    "necessarily", "negotiation", "neighboring", "nightingale", "nonetheless", "observation",
    "opportunity", "orientation", "originality", "paperweight", "parachuting", "partnership",
    "penetration", "performance", "personality", "perspective", "photography", "possibility",
    "potentially", "prehistoric", "preparation", "principally", "probability", "programming",
    "progressive", "publication", "punctuation", "quicksilver", "realization", "recognition",
    "refreshment", "remembrance", "requirement", "respectable", "responsible", "restoration",
    "scholarship", "scrumptious", "sensational", "sensitivity", "significant", "spectacular",
    "springboard", "stimulation", "substantial", "supervision", "sustainable", "sympathetic",
    "temperament", "temperature", "terminology", "threatening", "thunderbolt", "traditional",
    "transaction", "translation", "transparent", "uncertainty", "underground", "undertaking",
    "unfortunate", "universally", "unnecessary", "unrealistic", "vacationing", "vaccination",
    "volunteered", "warehousing", "whereabouts", "workmanship",
  ],
  12: [
    "accidentally", "accompanying", "accomplished", "afterthought", "alphabetical", "amphitheater",
    "anticipation", "appreciation", "breakthrough", "championship", "choreography", "circumstance",
    "collectively", "commissioner", "concentrated", "confirmation", "congratulate", "congregation",
    "conservation", "considerable", "constructing", "construction", "consultation", "contemporary",
    "continuously", "contribution", "conversation", "coordination", "deregulation", "disagreement",
    "disappointed", "disastrously", "distribution", "economically", "embarrassing", "encyclopedia",
    "entertaining", "enthusiastic", "entrepreneur", "exhilarating", "experimental", "friendliness",
    "hippopotamus", "historically", "horsemanship", "housekeeping", "humanitarian", "hypothetical",
    "illustration", "inauguration", "incandescent", "incidentally", "inconvenient", "increasingly",
    "independence", "installation", "intellectual", "intelligence", "intermediate", "intervention",
    "introduction", "manipulation", "mathematical", "mechanically", "metropolitan", "moonlighting",
    "mysteriously", "neighborhood", "nonrenewable", "northeastern", "notification", "organization",
    "oversleeping", "passionately", "perseverance", "photographer", "pleasantness", "prescription",
    "presentation", "preservation", "presidential", "professional", "psychiatrist", "refrigerator",
    "registration", "rehabilitate", "relationship", "relentlessly", "reproduction", "respectfully",
    "respectively", "satisfaction", "screenwriter", "shortsighted", "simultaneous", "skateboarder",
    "sleepwalking", "snowboarding", "sportscaster", "strengthened", "subconscious", "subscription",
    "substitution", "successfully", "surveillance", "thoroughfare", "transmission", "triumphantly",
    "unbelievable", "unemployment", "unrestricted", "verification", "veterinarian",
  ],
  13: [
    "appropriately", "argumentative", "authoritative", "autobiography", "biotechnology", "collaboration",
    "commemoration", "comprehension", "comprehensive", "concentration", "confrontation", "conscientious",
    "considerately", "consideration", "constellation", "contamination", "counterattack", "deforestation",
    "demonstration", "determination", "disappearance", "documentation", "dysfunctional", "effectiveness",
    "encouragement", "enlightenment", "entertainment", "environmental", "establishment", "exceptionally",
    "extraordinary", "fundamentally", "gravitational", "imaginatively", "impossibility", "incontestable",
    "incorporation", "independently", "individuality", "inexperienced", "inspirational", "investigation",
    "manufacturing", "mediterranean", "microorganism", "miscellaneous", "misunderstand", "opportunities",
    "participation", "possibilities", "qualification", "questionnaire", "reforestation", "revolutionary",
    "significantly", "sophisticated", "specification", "understanding", "unfortunately", "unpredictable",
    "vegetarianism", "visualization", "vulnerability",
  ],
  14: [
    "accountability", "acknowledgment", "administration", "administrative", "classification", "comprehensible",
    "constitutional", "disappointment", "discouragement", "discrimination", "fundamentalism", "implementation",
    "indistinctness", "industrialized", "infrastructure", "intellectually", "interconnected", "interpretation",
    "multiplication", "nanotechnology", "overcompensate", "overpopulation", "overprotective", "philanthropist",
    "photosynthesis", "recommendation", "reconciliation", "reconstruction", "rehabilitation", "representation",
    "responsibility", "responsiveness", "superintendent", "transformation", "transportation", "uncontrollable",
    "unconventional", "underestimated", "understatement",
  ],
  15: [
    "characteristics", "congratulations", "counterargument", "deindustrialize", "disillusionment", "extraordinarily",
    "incompatibility", "inconspicuously", "individualistic", "interdependence", "internationally", "overachievement",
    "overcomplicated", "overrepresented", "philosophically", "photojournalism", "professionalism", "psychologically",
    "reconceptualize", "recontextualize", "revolutionizing", "straightforward", "telecommunicate", "unconditionally",
    "underestimation", "underpopulation", "unsophisticated", "unsportsmanlike",
  ],
  16: [
    "characterization", "compartmentalism", "compartmentalize", "counterintuitive", "disestablishment", "disproportionate",
    "electromagnetism", "entrepreneurship", "environmentalism", "extraterrestrial", "hypersensitivity", "hyperventilating",
    "immunodeficiency", "incomprehensible", "incontrovertible", "institutionalize", "internationalism", "internationalize",
    "irresponsibility", "microengineering", "misappropriation", "misunderstanding", "multiculturalism", "multidimensional",
    "overcompensation", "transcontinental", "unaccountability", "uncharacteristic", "uncompromisingly", "unconstitutional",
    "unconventionally", "underachievement", "underappreciated", "underrepresented", "unsustainability",
  ],
  17: [
    "constitutionality", "counterproductive", "indistinguishable", "industrialization", "institutionalized", "interdisciplinary",
    "intergovernmental", "internationalized", "interrelationship", "irreproducibility", "misrepresentation", "nondiscriminatory",
    "overqualification", "telecommunication",
  ],
  18: [
    "deinstitutionalize", "disproportionately", "interconnectedness", "overgeneralization", "underqualification",
  ],
  19: [
    "counterproductively", "deindustrialization", "professionalization", "reindustrialization",
  ],
  20: [
    "counterrevolutionary", "internationalization",
  ],
};

export const MIN_WORD_LENGTH = 4;
export const MAX_WORD_LENGTH = 20;