// FALLBACK word bank, keyed by word length (4 through 20 letters).
// This ~3,500-word curated list ships inside the repo and is used ONLY if
// the real dictionary (300,000+ words, fetched from a public word list at
// server startup - see dictionary.js) can't be loaded, e.g. no internet
// access at boot. This guarantees the game ALWAYS works, even fully
// offline, just with a smaller word pool until connectivity returns.
// (No offensive or obscure words - safe for a public livestream.)

export const MIN_WORD_LENGTH = 4;
export const MAX_WORD_LENGTH = 20;
export const WORD_LENGTH_OPTIONS = [];
for (let n = MIN_WORD_LENGTH; n <= MAX_WORD_LENGTH; n++) WORD_LENGTH_OPTIONS.push(n);

export const FALLBACK_WORD_LISTS = {
  4: [
    "able", "acid", "aged", "also", "area", "army", "away", "baby", "back", "ball",
    "band", "bank", "base", "bath", "bear", "beat", "been", "beer", "bell", "belt",
    "best", "bike", "bill", "bird", "blue", "boat", "body", "bomb", "bond", "bone",
    "book", "boom", "born", "boss", "both", "bowl", "boys", "bulk", "burn", "bush",
    "busy", "cake", "call", "calm", "came", "camp", "card", "care", "case", "cash",
    "cast", "cave", "cell", "chat", "chip", "city", "club", "coal", "coat", "code",
    "cold", "come", "cook", "cool", "cope", "copy", "core", "cost", "crew", "crop",
    "dark", "data", "date", "dawn", "dead", "deal", "dear", "debt", "deep", "deny",
    "desk", "dial", "diet", "dirt", "dish", "disk", "dive", "does", "done", "door",
    "dose", "down", "draw", "drop", "drug", "drum", "dual", "duke", "dust", "duty",
    "each", "earn", "ease", "east", "easy", "edge", "else", "even", "ever", "evil",
    "exit", "face", "fact", "fail", "fair", "fall", "farm", "fast", "fate", "fear",
    "feed", "feel", "feet", "fell", "felt", "file", "fill", "film", "find", "fine",
    "fire", "firm", "fish", "five", "flag", "flat", "flee", "flew", "flow", "food",
    "foot", "ford", "form", "fort", "four", "free", "from", "fuel", "full", "fund",
    "gain", "game", "gate", "gave", "gear", "gene", "gift", "girl", "give", "glad",
    "goal", "goes", "gold", "golf", "gone", "good", "grab", "gray", "grew", "grey",
    "grid", "grip", "grow", "gulf", "hair", "half", "hall", "hand", "hang", "hard",
    "harm", "hate", "have", "head", "hear", "heat", "held", "hell", "help", "herb",
    "here", "hero", "hide", "high", "hill", "hire", "hold", "hole", "holy", "home",
    "hope", "host", "hour", "huge", "hung", "hunt", "hurt", "icon", "idea", "into",
    "iron", "item", "jazz", "join", "joke", "jump", "jury", "just", "keen", "keep",
    "kept", "kick", "kill", "kind", "king", "kiss", "knee", "knew", "know", "lack",
    "lady", "lake", "land", "lane", "last", "late", "lawn", "lead", "leaf", "lean",
    "left", "less", "life", "lift", "like", "line", "link", "lion", "list", "live",
    "load", "loan", "lock", "logo", "lone", "long", "look", "lord", "lose", "loss",
    "lost", "loud", "love", "luck", "lump", "lung", "made", "mail", "main", "make",
    "male", "mall", "many", "mark", "mask", "mass", "mate", "meal", "mean", "meat",
    "meet", "menu", "mere", "mile", "milk", "mind", "mine", "mint", "miss", "mode",
    "mood", "moon", "more", "most", "move", "much", "must", "myth", "name", "navy",
    "near", "neat", "neck", "need", "news", "next", "nice", "nine", "none", "nose",
    "note", "oath", "once", "only", "onto", "open", "oral", "over", "pace", "pack",
    "page", "paid", "pain", "pair", "pale", "palm", "park", "part", "pass", "past",
    "path", "peak", "peer", "pick", "pile", "pill", "pink", "pipe", "plan", "play",
    "plot", "plug", "plus", "poem", "poet", "pole", "poll", "pool", "poor", "port",
    "pose", "post", "pour", "pray", "prep", "prey", "pull", "pump", "pure", "push",
    "race", "rack", "rage", "raid", "rail", "rain", "rank", "rare", "rate", "read",
    "real", "rear", "rely", "rent", "rest", "rice", "rich", "ride", "ring", "rise",
    "risk", "road", "rock", "role", "roll", "roof", "room", "root", "rope", "rose",
    "rule", "rush", "rust", "safe", "sail", "sake", "sale", "salt", "same", "sand",
    "save", "scan", "seal", "seat", "seed", "seek", "seem", "seen", "self", "sell",
    "send", "sent", "ship", "shoe", "shop", "shot", "show", "shut", "sick", "side",
    "sign", "silk", "sing", "site", "size", "skin", "skip", "slam", "slip", "slot",
    "slow", "snap", "snow", "soap", "sock", "soft", "soil", "sold", "sole", "some",
    "song", "soon", "sort", "soul", "soup", "sour", "spin", "spot", "star", "stay",
    "stem", "step", "stir", "stop", "such", "suit", "sure", "swap", "swim", "tail",
    "take", "tale", "talk", "tall", "tank", "tape", "task", "team", "tear", "tell",
    "tend", "tent", "term", "test", "text", "than", "that", "thin", "this", "thus",
    "tide", "tidy", "tied", "tier", "till", "time", "tiny", "tire", "told", "toll",
    "tone", "took", "tool", "tour", "town", "toys", "trap", "tree", "trim", "trip",
    "true", "tube", "tune", "turn", "twin", "type", "unit", "upon", "urge", "used",
    "user", "vary", "vast", "very", "veto", "view", "vote", "wage", "wait", "wake",
    "walk", "wall", "want", "ward", "warm", "warn", "wash", "wave", "ways", "weak",
    "wear", "week", "well", "went", "were", "west", "what", "when", "whom", "wide",
    "wife", "wild", "will", "wind", "wine", "wing", "wire", "wise", "wish", "with",
    "wolf", "wood", "wool", "word", "wore", "work", "yard", "yarn", "year", "your",
    "zero", "zone", "zoom",
  ],
  5: [
    "about", "above", "abuse", "acorn", "actor", "acute", "admit", "adopt", "adore", "adorn",
    "adult", "afoot", "after", "again", "agent", "agile", "agree", "ahead", "aisle", "alarm",
    "album", "alert", "alike", "alive", "allot", "allow", "alloy", "alone", "along", "alter",
    "amber", "amend", "among", "amuse", "angel", "anger", "angle", "angry", "angst", "annoy",
    "apart", "apple", "apply", "aptly", "arena", "argue", "arise", "armor", "aroma", "array",
    "arrow", "ashen", "aside", "asset", "atlas", "audio", "audit", "avoid", "awake", "award",
    "aware", "awash", "awful", "axiom", "bacon", "badge", "baker", "balmy", "banjo", "barge",
    "basic", "basil", "basis", "batch", "baton", "beach", "beard", "beast", "begin", "being",
    "belly", "belts", "bench", "berry", "birth", "bison", "black", "blade", "blame", "blank",
    "blast", "blaze", "bleed", "blend", "bless", "blind", "blitz", "bloat", "block", "blood",
    "bloom", "blown", "blues", "blunt", "board", "boast", "bonus", "boost", "booth", "booty",
    "bossy", "bound", "brain", "brand", "brave", "bread", "break", "breed", "brick", "bride",
    "brief", "bring", "brisk", "broad", "broke", "brook", "broth", "brown", "brunt", "brush",
    "buddy", "build", "built", "bulge", "bumpy", "bunch", "bunny", "burly", "burst", "cabin",
    "cable", "cadet", "camel", "canal", "candy", "canoe", "caper", "carol", "carve", "catch",
    "cause", "cease", "chain", "chair", "chalk", "champ", "chant", "chaos", "charm", "chart",
    "chase", "cheap", "check", "cheer", "chess", "chest", "chief", "child", "chill", "chirp",
    "choir", "choke", "chomp", "chore", "chose", "chunk", "civic", "civil", "claim", "clash",
    "class", "clean", "clear", "clerk", "click", "cliff", "climb", "cling", "clock", "close",
    "cloth", "cloud", "clown", "cluck", "coach", "coast", "cobra", "comet", "const", "corny",
    "cough", "could", "count", "coupe", "court", "cover", "covet", "crack", "craft", "cramp",
    "crane", "crank", "crash", "crave", "crawl", "crazy", "cream", "credo", "creek", "crepe",
    "crest", "crime", "crisp", "crook", "cross", "crowd", "crown", "crude", "cruel", "crumb",
    "crush", "crypt", "cubic", "curly", "curry", "curve", "cycle", "daily", "dance", "dealt",
    "death", "debut", "decay", "decoy", "defer", "delay", "delta", "demon", "dense", "depth",
    "derby", "diary", "digit", "dingo", "dirty", "disco", "dizzy", "dodge", "donor", "donut",
    "doubt", "douse", "dowel", "dozen", "draft", "drain", "drama", "drank", "drape", "drawl",
    "drawn", "dread", "dream", "dregs", "dress", "dried", "drift", "drill", "drink", "drive",
    "droop", "drove", "drown", "drunk", "dryer", "dunce", "dusky", "eager", "eagle", "early",
    "earth", "easel", "eaten", "ebony", "ebook", "edges", "eject", "elbow", "elder", "elect",
    "elite", "elope", "email", "empty", "enact", "ended", "enjoy", "enter", "entry", "epoxy",
    "equal", "equip", "erase", "erode", "error", "essay", "ether", "event", "every", "evoke",
    "exact", "exalt", "exert", "exile", "exist", "extra", "fable", "faced", "facet", "facts",
    "faint", "fairy", "faith", "false", "fancy", "fault", "fauna", "favor", "feast", "feign",
    "fella", "fence", "fetal", "fetch", "fever", "fiber", "field", "fiery", "fifth", "fifty",
    "fight", "final", "finch", "finer", "first", "fixed", "flags", "flair", "flake", "flame",
    "flank", "flash", "fleck", "fleet", "flesh", "flick", "flint", "float", "flock", "flood",
    "floor", "flour", "flout", "flows", "fluid", "flute", "focus", "foray", "force", "forge",
    "forgo", "forte", "forth", "forum", "found", "foyer", "frail", "frame", "frank", "fresh",
    "frisk", "front", "frost", "froze", "fruit", "fudge", "fungi", "gauge", "gauze", "gears",
    "gecko", "geese", "genre", "giant", "girth", "given", "gives", "glare", "glass", "gleam",
    "globe", "glory", "glove", "gnome", "going", "goofy", "gouge", "grace", "grade", "grain",
    "grand", "grant", "grape", "graph", "grasp", "grass", "grave", "gravy", "graze", "great",
    "greed", "green", "greet", "grief", "grill", "grimy", "grind", "grips", "groin", "groom",
    "grope", "gross", "group", "grout", "grove", "growl", "grown", "guard", "guess", "guest",
    "guide", "gully", "gusto", "habit", "hairy", "happy", "harsh", "haste", "haven", "hazel",
    "heard", "heart", "heavy", "hedge", "heist", "hence", "herbs", "hewer", "hills", "hinge",
    "hippo", "hoard", "hobby", "hoist", "hokey", "holly", "honey", "honky", "honor", "horse",
    "hotel", "hound", "house", "hovel", "hover", "human", "humid", "humor", "hurry", "hyena",
    "icing", "ideal", "igloo", "image", "imply", "index", "india", "inept", "infer", "inner",
    "input", "irony", "issue", "ivory", "jaded", "jazzy", "jelly", "joint", "joker", "jolly",
    "judge", "juice", "jumbo", "jumpy", "junky", "kayak", "kiosk", "knead", "kneel", "knelt",
    "knife", "knock", "known", "label", "labor", "laden", "lager", "lance", "large", "laser",
    "latch", "later", "latex", "laugh", "layer", "learn", "least", "leave", "legal", "lemon",
    "level", "lever", "light", "limit", "linen", "liver", "llama", "loamy", "lobby", "local",
    "lodge", "logic", "loopy", "loose", "lover", "lower", "loyal", "lucky", "lumpy", "lunar",
    "lunch", "lupus", "lying", "lymph", "macho", "magic", "major", "maker", "mango", "manic",
    "manor", "march", "marsh", "match", "mauve", "maybe", "mayor", "meant", "medal", "media",
    "mercy", "merge", "merit", "metal", "meter", "might", "mince", "minor", "minty", "minus",
    "mixed", "mocha", "model", "modem", "mogul", "money", "month", "moral", "mossy", "motto",
    "mould", "mount", "mouse", "mouth", "moved", "movie", "mucus", "mulch", "mural", "music",
    "naive", "naked", "nasal", "nasty", "naval", "nerve", "never", "newel", "newer", "newly",
    "nifty", "night", "noble", "noise", "nomad", "noose", "north", "notch", "novel", "nudge",
    "nurse", "nylon", "nymph", "obese", "ocean", "offal", "offer", "often", "olden", "olive",
    "onion", "onset", "opera", "opine", "orbit", "order", "organ", "other", "ought", "ounce",
    "outer", "ovary", "owlet", "owner", "ozone", "pagan", "panel", "panic", "paper", "party",
    "paste", "patch", "patio", "pause", "peace", "peach", "pearl", "pedal", "penny", "pesky",
    "petty", "phase", "phone", "photo", "piano", "piece", "piety", "pilot", "pitch", "pixel",
    "pizza", "place", "plaid", "plain", "plank", "plant", "plate", "plaza", "plead", "pluck",
    "plumb", "podge", "point", "poise", "poker", "polar", "polka", "porch", "pound", "power",
  ],
  6: [
    "accept", "access", "across", "action", "active", "actual", "advice", "afford", "afraid", "agency",
    "almost", "always", "amazed", "amount", "animal", "annual", "answer", "anyone", "appeal", "appear",
    "around", "arrive", "artist", "aspect", "assist", "assume", "attack", "attend", "august", "author",
    "autumn", "avenue", "backed", "banner", "barrel", "basket", "battle", "beauty", "become", "before",
    "behalf", "behave", "behind", "belief", "belong", "beside", "better", "beyond", "bishop", "border",
    "bottle", "bottom", "bought", "branch", "bridge", "bright", "broken", "budget", "burden", "bureau",
    "button", "camera", "campus", "cancel", "cancer", "candle", "canvas", "carbon", "career", "castle",
    "casual", "cellar", "center", "chance", "change", "chapel", "choice", "choose", "chosen", "church",
    "circle", "client", "closed", "closer", "coffee", "colony", "column", "combat", "comedy", "coming",
    "common", "comply", "copper", "corner", "costly", "cotton", "county", "couple", "course", "cousin",
    "create", "credit", "crisis", "custom", "damage", "dancer", "danger", "deadly", "dealer", "debate",
    "decade", "decide", "defeat", "define", "degree", "denial", "dental", "deputy", "derive", "design",
    "desire", "detail", "detect", "device", "devote", "differ", "dining", "dinner", "direct", "doctor",
    "domain", "double", "dragon", "drawer", "driven", "driver", "during", "easily", "editor", "effect",
    "effort", "eighty", "either", "eleven", "embark", "empire", "enable", "ending", "energy", "engage",
    "engine", "enough", "ensure", "entity", "equity", "escape", "estate", "ethnic", "exceed", "except",
    "excess", "excite", "excuse", "exempt", "exotic", "expand", "expect", "expert", "export", "expose",
    "extend", "extent", "fabric", "factor", "fairly", "fallen", "family", "famous", "fasten", "father",
    "favour", "feared", "female", "figure", "filing", "finale", "finger", "finish", "fiscal", "flavor",
    "flight", "floral", "flying", "folder", "follow", "forbid", "forces", "forest", "forget", "formal",
    "format", "former", "foster", "fourth", "freely", "friend", "frozen", "future", "galaxy", "gallon",
    "garage", "garden", "gather", "gender", "genius", "gentle", "giving", "global", "golden", "gospel",
    "govern", "grades", "ground", "growth", "guilty", "guitar", "hammer", "handle", "happen", "harbor",
    "hardly", "hatred", "header", "health", "hearty", "heaven", "height", "helmet", "hidden", "higher",
    "highly", "hockey", "holder", "honest", "horror", "hostel", "humble", "hunger", "hunter", "ignore",
    "impact", "import", "income", "indeed", "indoor", "inform", "injury", "inline", "inmate", "insect",
    "inside", "insist", "intact", "invest", "invite", "island", "itself", "jacket", "jargon", "jersey",
    "jigsaw", "jockey", "jungle", "junior", "kernel", "kidney", "kindly", "kitten", "ladder", "latter",
    "launch", "lawyer", "leader", "league", "legacy", "legend", "lesson", "letter", "liable", "likely",
    "liquid", "listen", "little", "living", "locate", "locker", "lonely", "longer", "loving", "luxury",
    "madame", "magnet", "mainly", "makeup", "manage", "manner", "manual", "margin", "marine", "marker",
    "market", "marvel", "master", "matter", "mature", "meadow", "medium", "member", "memory", "mental",
    "mentor", "merely", "merger", "method", "middle", "mighty", "mining", "minute", "mirror", "mobile",
    "modern", "modest", "module", "monkey", "morale", "mostly", "mother", "motion", "motive", "muscle",
    "museum", "mutual", "myself", "narrow", "nation", "native", "nature", "nearby", "needed", "nephew",
    "nickel", "nimble", "ninety", "notice", "notion", "number", "object", "obtain", "occupy", "office",
    "oldest", "onward", "opened", "opener", "oppose", "option", "orange", "origin", "others", "outfit",
    "output", "oxygen", "packed", "palace", "parent", "parish", "partly", "patent", "patrol", "patron",
    "pencil", "people", "pepper", "period", "permit", "person", "phrase", "picked", "picnic", "pillar",
    "pistol", "planet", "plenty", "pocket", "poetry", "police", "policy", "polish", "potato", "powder",
    "prayer", "prefer", "pretty", "priest", "prince", "prison", "profit", "proper", "proven", "public",
    "pursue", "puzzle", "python", "quaint", "quirky", "rabbit", "racket", "random", "rarely", "rather",
    "rating", "ration", "reader", "really", "reason", "recall", "recent", "record", "reduce", "refuse",
    "regard", "regime", "region", "reject", "relate", "relief", "remain", "remedy", "remind", "remote",
    "remove", "rental", "repair", "repeat", "replay", "report", "rescue", "resign", "resist", "resort",
    "result", "retail", "retain", "retire", "return", "reveal", "review", "reward", "rhythm", "riddle",
    "rocket", "rotate", "rubber", "rugged", "ruling", "runner", "safety", "sample", "saving", "savior",
    "scheme", "school", "scoops", "screen", "script", "search", "season", "second", "sector", "secure",
    "seldom", "select", "seller", "senior", "sensor", "series", "settle", "severe", "shadow", "shaken",
    "shanty", "shaped", "shaper", "sheets", "shield", "shiner", "silent", "silver", "simple", "singer",
    "single", "sister", "sitter", "skater", "sketch", "slight", "smooth", "social", "socket", "solely",
    "solved", "somber", "sordid", "sorrow", "sorted", "source", "spared", "sparse", "speech", "spirit",
    "spoken", "spring", "sprint", "square", "squash", "stable", "starve", "statue", "status", "steady",
    "stereo", "sticky", "storey", "stormy", "strain", "strand", "stream", "street", "strict", "strike",
    "string", "strive", "strong", "studio", "sturdy", "submit", "sudden", "suffer", "summer", "summit",
    "sunset", "superb", "supply", "surely", "survey", "switch", "symbol", "system", "tablet", "tackle",
    "talent", "target", "tavern", "temple", "tenant", "tender", "tennis", "tenure", "thanks", "theory",
    "thirst", "though", "thread", "threat", "thrown", "thrust", "ticket", "tissue", "toilet", "tomato",
    "tongue", "toward", "travel", "treaty", "trendy", "tribal", "trophy", "tunnel", "turkey", "tutors",
    "twenty", "unable", "unfold", "unique", "united", "unless", "unlike", "update", "upload", "uproar",
    "upward", "urgent", "usable", "useful", "vacant", "valley", "valued", "vanish", "vendor", "verbal",
    "verify", "versus", "vessel", "victim", "viewer", "vision", "visual", "volume", "voting", "voyage",
    "wander", "warmth", "weapon", "weight", "wheels", "widget", "window", "winner", "winter", "wisdom",
    "within", "wonder", "wooden", "worker", "worthy", "writer", "yellow", "zoning",
  ],
  7: [
    "amazing", "ancient", "article", "between", "brought", "capital", "capsule", "caravan", "chapter", "chicken",
    "comfort", "company", "concept", "contact", "contain", "control", "cricket", "crystal", "culture", "curious",
    "current", "cushion", "deliver", "dentist", "desktop", "develop", "digital", "discuss", "disease", "display",
    "dolphin", "doorway", "dynasty", "economy", "elegant", "embrace", "emotion", "enhance", "episode", "evening",
    "exactly", "examine", "example", "exclude", "execute", "exhibit", "expense", "explain", "explore", "express",
    "extreme", "factory", "fashion", "feather", "feature", "federal", "fiction", "fifteen", "fishing", "flavour",
    "forever", "forward", "framing", "freedom", "further", "gadgets", "garbage", "gateway", "general", "genuine",
    "giraffe", "glacier", "gravity", "grocery", "hallway", "harmony", "harvest", "headset", "helpful", "highway",
    "history", "holiday", "hostile", "however", "hundred", "husband", "imagine", "implant", "imports", "improve",
    "include", "initial", "insight", "inspect", "install", "instant", "isolate", "journal", "journey", "justice",
    "justify", "kitchen", "lantern", "laundry", "lecture", "liberty", "license", "limited", "listing", "machine",
    "magical", "mailbox", "mammoth", "manager", "mandate", "mansion", "mapping", "marbles", "married", "mastery",
    "maximum", "meaning", "measure", "medical", "melting", "mention", "message", "migrant", "million", "mineral",
    "minimum", "mission", "mixture", "modesty", "monitor", "morning", "musical", "mystery", "natural", "neither",
    "network", "neutral", "newborn", "nowhere", "nuclear", "nursery", "obscure", "obvious", "offense", "opening",
    "operate", "opinion", "optical", "organic", "outcome", "outdoor", "package", "painter", "parking", "partner",
    "passage", "passion", "patient", "payment", "penalty", "pending", "perfect", "perform", "perhaps", "picture",
    "pioneer", "plastic", "playful", "pleased", "plumber", "pointer", "popular", "portion", "poultry", "prairie",
    "precise", "predict", "prepare", "present", "pretend", "primary", "printer", "privacy", "private", "problem",
    "process", "produce", "product", "profile", "program", "project", "promise", "propose", "protect", "protein",
    "provide", "publish", "purpose", "pursuit", "quality", "quantum", "quarter", "radiant", "rainbow", "reading",
    "realize", "receipt", "receive", "recover", "reflect", "refresh", "regular", "related", "release", "remains",
    "replace", "request", "require", "reserve", "resolve", "respect", "respond", "restore", "retreat", "reunion",
    "revenue", "reverse", "routine", "satisfy", "scatter", "science", "section", "segment", "seminar", "sensory",
    "service", "session", "several", "shampoo", "shatter", "shelter", "shipped", "shortly", "silence", "similar",
    "skilled", "slavery", "society", "soldier", "sponsor", "stadium", "stomach", "storage", "strange", "stretch",
    "student", "subject", "succeed", "suggest", "summary", "support", "surface", "surgery", "surplus", "survive",
    "suspect", "sustain", "teacher", "teenage", "terrain", "texture", "thereby", "thinker", "thought", "through",
    "tonight", "tourist", "tragedy", "trainer", "treated", "trouble", "tuition", "turnout", "uniform", "unknown",
    "unusual", "upgrade", "uploads", "vacancy", "vantage", "variant", "variety", "various", "venture", "verdict",
    "version", "vibrant", "village", "vintage", "virtual", "visible", "vitamin", "voyager", "warfare", "warning",
    "wealthy", "weather", "welcome", "welfare", "whisper", "winning", "without", "working", "workout", "worried",
    "yielded",
  ],
  8: [
    "absolute", "abstract", "academic", "accepted", "accurate", "activity", "actually", "addition", "adequate", "admitted",
    "advanced", "aircraft", "alphabet", "although", "aluminum", "ambition", "analysis", "ancestor", "announce", "anything",
    "anywhere", "apparent", "appendix", "arranged", "artistic", "assemble", "assembly", "assigned", "athletic", "attitude",
    "audience", "backpack", "bacteria", "baseball", "birthday", "blockade", "boundary", "building", "business", "calendar",
    "campaign", "capacity", "cardinal", "cautious", "ceremony", "champion", "chemical", "children", "cinnamon", "civilian",
    "classify", "clinical", "colonial", "colorful", "combined", "commerce", "commonly", "compared", "compiler", "complete",
    "composed", "computer", "conclude", "concrete", "conflict", "confused", "congress", "consider", "constant", "continue",
    "contract", "contrast", "controls", "convince", "cookbook", "cosmetic", "creative", "criminal", "critical", "cucumber",
    "currency", "database", "daughter", "daydream", "deadline", "december", "decision", "decrease", "dedicate", "delicate",
    "delivery", "describe", "designer", "detailed", "detector", "diagnose", "dialogue", "diameter", "director", "disabled",
    "disaster", "discount", "discover", "disorder", "distance", "district", "dividend", "division", "doctrine", "document",
    "domestic", "dominant", "doorknob", "doubtful", "dramatic", "dressing", "dropdown", "earnings", "eastward", "economic",
    "educated", "election", "electric", "elephant", "elevator", "eligible", "emerging", "emphasis", "employee", "enormous",
    "entrance", "envelope", "equation", "escalate", "estimate", "evacuate", "evaluate", "everyday", "evidence", "exchange",
    "exercise", "existing", "expected", "explicit", "exposure", "external", "eyebrows", "families", "favorite", "feedback",
    "festival", "filename", "finalize", "firewall", "flagship", "flexible", "football", "forecast", "foreword", "formerly",
    "fraction", "fragment", "frequent", "function", "gasoline", "gemstone", "generate", "generous", "gigantic", "giveaway",
    "governor", "graduate", "grateful", "guidance", "handling", "hardware", "headline", "heritage", "historic", "horrible",
    "hospital", "humanity", "humorous", "identity", "ignorant", "illusion", "imagined", "imperial", "imprison", "incident",
    "increase", "indicate", "indirect", "industry", "infamous", "informal", "informed", "initiate", "innocent", "insomnia",
    "inspired", "instance", "instinct", "integral", "intended", "interact", "interest", "interior", "internal", "interval",
    "intimate", "invasion", "invasive", "involved", "isolated", "judgment", "junction", "keyboard", "kilogram", "kindness",
    "landmark", "language", "lavender", "lawmaker", "learning", "lifelong", "lifetime", "likewise", "literacy", "literary",
    "location", "longterm", "magnetic", "mainland", "majority", "mandarin", "marginal", "marriage", "massacre", "material",
    "maternal", "maturity", "meantime", "medicine", "medieval", "memorial", "merchant", "metallic", "midnight", "migrated",
    "mistaken", "mobility", "moderate", "modified", "momentno", "momentum", "monetary", "monument", "moreover", "mortgage",
    "mountain", "movement", "multiple", "mushroom", "national", "negative", "neighbor", "nickname", "nominate", "notebook",
    "november", "nutshell", "obedient", "observer", "occupied", "offering", "official", "offshore", "operator", "opposite",
    "optimism", "ordinary", "organism", "organize", "original", "outbreak", "outdoors", "outreach", "overcoat", "overcome",
    "overflow", "overlook", "overseas", "overview", "painting", "pandemic", "parallel", "parental", "parkland", "particle",
    "passport", "pastoral", "patience", "pavement", "peaceful", "peculiar", "pedestal", "pendulum", "perceive", "periodic",
    "personal", "physical", "pipeline", "platform", "plumbing", "politics", "portable", "portrait", "position", "positive",
    "possible", "powerful", "practice", "precious", "predicts", "pregnant", "pressure", "previous", "princess", "printout",
    "priority", "probable", "problems", "produced", "producer", "profound", "progress", "prohibit", "projects", "property",
    "proposal", "prospect", "protocol", "provided", "provider", "province", "publicly", "purchase", "purified", "pyramids",
    "quantity", "question", "radiator", "rational", "reaction", "readable", "receiver", "recently", "recorder", "recovery",
    "redesign", "reformed", "refugees", "regional", "register", "regulate", "relative", "relevant", "reliable", "religion",
    "remember", "reminder", "renowned", "repeated", "resemble", "resident", "resource", "response", "restrict", "revealed",
    "reversal", "ridicule", "romantic", "rotation", "sandwich", "scenario", "schedule", "scrutiny", "seasonal", "sediment",
    "selected", "sensible", "sequence", "severity", "shipping", "shortage", "shoulder", "sidewalk", "simplify", "situated",
    "skeleton", "slightly", "softball", "solution", "somebody", "southern", "spacious", "speaking", "specimen", "spectrum",
    "spelling", "spirited", "sprinkle", "stairway", "standard", "stardust", "sterling", "stimulus", "straight", "strategy",
    "strength", "striking", "strongly", "struggle", "stunning", "subtlety", "suburban", "suitable", "sunlight", "superior",
    "supplier", "surprise", "surround", "survival", "sympathy", "symphony", "syndrome", "synopsis", "tailored", "takeover",
    "tangible", "teamwork", "teardrop", "telecast", "template", "temporal", "tendency", "terminal", "terrible", "thankful",
    "theology", "thorough", "thousand", "timeline", "together", "tomorrow", "tradeoff", "training", "transfer", "treasure",
    "triangle", "tropical", "turbines", "ultimate", "umbrella", "uncommon", "underway", "universe", "unlawful", "unlikely",
    "unwanted", "upcoming", "vacation", "vacuumed", "valuable", "vertical", "veterans", "villages", "violence", "visitors",
    "volatile", "warranty", "weakness", "wildfire", "wildlife", "workflow", "workshop", "yourself",
  ],
  9: [
    "according", "afternoon", "aggregate", "agreement", "algorithm", "allocated", "amendment", "amplitude", "ancestors", "annoyance",
    "apartment", "apologize", "appliance", "appointed", "apprehend", "architect", "arguments", "assurance", "attention", "automatic",
    "available", "blueprint", "boulevard", "brilliant", "broadcast", "butterfly", "calculate", "candidate", "carnivore", "cartridge",
    "cathedral", "celebrate", "celebrity", "certainly", "challenge", "checklist", "chocolate", "cigarette", "circulate", "classroom",
    "coastline", "colleague", "collision", "commander", "committee", "community", "component", "composite", "concealed", "congenial",
    "connected", "consensus", "consonant", "contained", "container", "contented", "continent", "copyright", "corporate", "correctly",
    "counselor", "courtroom", "coworkers", "creatures", "crossroad", "customary", "dangerous", "deceptive", "decisions", "decorated",
    "defensive", "delicious", "demanding", "departure", "dependent", "designate", "desperate", "developer", "diagnosis", "different",
    "dimension", "direction", "disappear", "discourse", "disturbed", "dominated", "downgrade", "dwindling", "ecosystem", "education",
    "effective", "efficient", "elaborate", "elemental", "eloquence", "emergency", "enclosure", "encounter", "endeavour", "endurance",
    "engineers", "enjoyable", "entertain", "equipment", "escalator", "essential", "establish", "estimated", "everybody", "evolution",
    "excellent", "exception", "excessive", "exclusive", "expansion", "expensive", "extension", "fabricate", "factorial", "familiars",
    "fantastic", "favorable", "feathered", "federated", "festivity", "financial", "fireplace", "flattened", "footprint", "forbidden",
    "forgotten", "formation", "fortunate", "fragrance", "frontline", "furniture", "generator", "glassware", "grassland", "greatness",
    "gymnastic", "handshake", "happiness", "harmonize", "heartbeat", "helpfully", "highlight", "homeowner", "honorable", "hurricane",
    "identical", "imaginary", "immediate", "immigrant", "important", "inability", "incentive", "inclusion", "inclusive", "incorrect",
    "indicator", "inference", "influence", "initially", "injection", "inquiries", "insertion", "inspector", "insurance", "intellect",
    "interface", "interpret", "interview", "intricate", "introduce", "involving", "irregular", "isolation", "kilometer", "knowledge",
    "landscape", "lastingly", "launching", "lawlessly", "legendary", "lifestyle", "lightbulb", "limestone", "livestock", "locksmith",
    "logically", "lucrative", "machinery", "mainframe", "maintains", "manifesto", "marketing", "masterful", "mechanism", "memorable",
    "merriment", "metabolic", "migration", "militants", "miserable", "momentous", "narrative", "navigator", "necessary", "negotiate",
    "newcomers", "nightmare", "notorious", "nutrition", "observant", "obviously", "operation", "outlander", "overnight", "overthrow",
    "overwhelm", "passenger", "patriotic", "pediatric", "penetrate", "permanent", "personnel", "physician", "placement", "plentiful",
    "potential", "premature", "prescribe", "president", "primitive", "principal", "principle", "privilege", "procedure", "prominent",
    "promising", "publisher", "qualified", "quotation", "radiation", "ratepayer", "reception", "recognize", "regretful", "rehearsal",
    "reinforce", "relatable", "reluctant", "residence", "resilient", "resources", "retention", "satellite", "scattered", "scenarios",
    "scientist", "scrapbook", "seemingly", "selection", "sensation", "separated", "sequences", "shattered", "shipwreck", "sidewalks",
    "signature", "snowflake", "somewhere", "specialty", "spiritual", "statement", "stimulate", "storyline", "strategic", "structure",
    "subscribe", "substance", "summarize", "supported", "sustained", "symbolize", "systemize", "tableware", "tarnished", "telephone",
    "temporary", "tentative", "topically", "tradition", "trainable", "transform", "translate", "transport", "traveling", "treatment",
    "tributary", "uncertain", "unchanged", "unfolding", "universal", "upgrading", "valuables", "variation", "vegetable", "vehicular",
    "ventilate", "versatile", "violation", "visionary", "volunteer", "warehouse", "waterfall", "wholesome", "wonderful", "workspace",
    "worldwide",
  ],
  10: [
    "absolutely", "accessible", "adjustment", "adventures", "articulate", "aspiration", "assistance", "atmosphere", "attractive", "characters",
    "comforting", "commentary", "complexity", "compulsory", "concerning", "concession", "confession", "confidence", "contribute", "definitely",
    "department", "dictionary", "discipline", "earthquake", "employment", "enthusiasm", "fellowship", "formidable", "foundation", "fraudulent",
    "friendship", "generation", "government", "graduation", "greenhouse", "guidelines", "helicopter", "hemisphere", "horizontal", "hypothesis",
    "identifier", "illiterate", "inequality", "ingredient", "inhabitant", "instructor", "instrument", "investment", "jubilation", "leadership",
    "linguistic", "literature", "management", "metropolis", "microscope", "misfortune", "morphology", "motivation", "mysterious", "occasional",
    "opposition", "originated", "overweight", "perceptive", "persistent", "philosophy", "pilgrimage", "population", "possession", "precaution",
    "prediction", "preference", "priorities", "productive", "profitable", "protective", "provisions", "punishment", "recreation", "reflective",
    "registered", "relatively", "remarkable", "repertoire", "reputation", "responsive", "restaurant", "retirement", "revelation", "revolution",
    "rhinoceros", "scoreboard", "settlement", "silhouette", "simplicity", "skyscraper", "solidarity", "splendidly", "stationary", "statistics",
    "struggling", "successful", "supervisor", "surrounded", "technician", "technology", "thankfully", "thoughtful", "timeliness", "tremendous",
    "triangular", "underlying", "understand", "undertaken", "unfamiliar", "unforeseen", "vertebrate", "victorious", "vocabulary", "volleyball",
    "wavelength", "westernize",
  ],
  11: [
    "achievement", "application", "appointment", "arrangement", "association", "celebration", "combination", "conditional", "cooperation", "corporation",
    "development", "enlargement", "environment", "examination", "exploration", "feasibility", "frustration", "grandfather", "grandmother", "imagination",
    "improvement", "information", "inspiration", "involvement", "measurement", "millionaire", "observation", "opportunity", "perspective", "positioning",
    "preparation", "prospective", "publication", "queenmother", "realization", "renaissance", "replacement", "requirement", "reservation", "restoration",
    "significant", "terrestrial", "theoretical", "trustworthy", "utilization", "vaccination",
  ],
  12: [
    "announcement", "architecture", "championship", "choreography", "conversation", "disagreement", "illustration", "independence", "introduction", "legalization",
    "localization", "maximization", "minimization", "mobilization", "optimization", "organization", "particularly", "photographic", "presentation", "refrigerator",
    "regeneration", "registration", "relationship", "surveillance", "unbelievable", "unbelievably", "unimaginable",
  ],
  13: [
    "authorization", "autobiography", "certification", "collaboration", "communication", "consideration", "demonstration", "determination", "documentation", "dramatization",
    "encouragement", "entertainment", "establishment", "extraordinary", "globalization", "inconceivable", "indispensable", "international", "investigation", "irresponsible",
    "manufacturing", "modernization", "normalization", "opportunities", "privatization", "qualification", "questionnaire", "recognization", "revolutionary", "socialization",
    "specification", "stabilization", "sterilization", "summarization", "systemization", "uncomfortable", "underestimate", "understanding", "unforgettable", "victimization",
    "visualization", "vulnerability",
  ],
  14: [
    "accountability", "administration", "capitalization", "categorization", "characteristic", "classification", "constitutional", "conventionally", "disappointment", "discrimination",
    "generalization", "geographically", "identification", "implementation", "infrastructure", "monopolization", "neutralization", "occupationally", "overpopulation", "popularization",
    "professionally", "recommendation", "representative", "responsibility", "revitalization", "simplification", "specialization", "sustainability", "transformation", "transportation",
    "uncontrollably", "unconventional", "unquestionably", "westernization",
  ],
  15: [
    "characteristics", "computerization", "confidentiality", "confrontational", "congratulations", "crystallization", "democratization", "diversification", "entrepreneurial", "extraordinarily",
    "hospitalization", "immortalization", "incompatibility", "individualistic", "intensification", "internationally", "nationalization", "overcomplicated", "personalization", "philosophically",
    "professionalism", "psychologically", "rationalization", "reconceptualize", "standardization", "straightforward", "synchronization", "technologically", "underprivileged",
  ],
  16: [
    "administratively", "characterization", "counterarguments", "counterintuitive", "decentralization", "decontextualized", "disingenuousness", "disproportionate", "entrepreneurship", "environmentalist",
    "hypersensitivity", "hyperventilating", "incomprehensible", "incomprehensibly", "internationalize", "interoperability", "misappropriation", "misunderstanding", "multiculturalism", "multidimensional",
    "overenthusiastic", "uncharacteristic", "unconstitutional", "underachievement", "unpredictability", "unsustainability",
  ],
  17: [
    "antiestablishment", "commercialization", "comprehensiveness", "counterproductive", "deconstructionist", "incompatibilities", "indistinguishable", "indistinguishably", "industrialization", "institutionalized",
    "interdependencies", "interdisciplinary", "misappropriations", "misclassification", "misinterpretation", "misunderstandings", "nondiscriminatory", "overqualification", "straightforwardly", "telecommunication",
    "uncontrollability", "underachievements", "unpredictableness",
  ],
  18: [
    "characteristically", "counterintuitively", "deinstitutionalize", "disenfranchisement", "disproportionately", "interconnectedness", "interrelationships", "misclassifications", "misinterpretations", "misrepresentations",
    "overgeneralization", "overprotectiveness", "overrepresentation", "oversimplification", "representativeness", "telecommunications", "unenthusiastically",
  ],
  19: [
    "comprehensivenesses", "counterproductively", "crossorganizational", "deindustrialization", "incomprehensibility", "interdisciplinarity", "overintellectualize", "oversimplifications", "professionalization", "uncommunicativeness",
    "underrepresentation",
  ],
  20: [
    "compartmentalization", "counterrevolutionary", "disproportionalities", "disproportionateness", "institutionalization", "internationalization", "noninstitutionalized", "overenthusiastically", "uncharacteristically",
  ],
};