// puzzles.js
// Each puzzle has a THEME and a list of words that all relate to it —
// this is the Findle mechanic: a themed set of hidden words,
// not a single scrambled word. Viewers guess theme words in chat;
// correct guesses are revealed and highlighted on the shared grid.
//
// Word length increases with difficulty, matching the real game's
// progression: Easy = 3-5 letters, Medium = 5-7 letters, Hard = 7-9 letters.
// Every tier has 50+ themed puzzles, each with 10+ words.

module.exports = {
  easy: [
    { theme: "Fruits", words: ["mango","grape","lemon","plum","kiwi","pear","date","fig","lime","melon","guava","apple"] },
    { theme: "Vegetables", words: ["pea","corn","kale","leek","okra","beet","yam","taro","onion","chard","gourd","chive"] },
    { theme: "Farm Animals", words: ["pig","cow","hen","ram","goat","duck","mule","lamb","calf","colt","foal","horse","sheep","goose"] },
    { theme: "Pizza Toppings", words: ["ham","egg","corn","herb","mint","onion","olive","basil","bacon","pesto","chili"] },
    { theme: "Colors", words: ["red","tan","gray","blue","gold","jade","pink","teal","ruby","ivory","coral","black","white","green","brown"] },
    { theme: "Kitchen Items", words: ["pot","pan","cup","jar","tray","bowl","fork","knife","spoon","plate","whisk","ladle"] },
    { theme: "Ocean Animals", words: ["cod","eel","ray","crab","clam","squid","shark","whale","seal","otter"] },
    { theme: "Breakfast Foods", words: ["egg","oat","jam","toast","bacon","syrup","bagel","gravy","crepe","grits"] },
    { theme: "School Supplies", words: ["pen","ink","glue","ruler","paper","chalk","book","desk","tape","clip"] },
    { theme: "Body Parts", words: ["arm","leg","ear","eye","rib","hip","jaw","chin","neck","knee","foot","hand","nose","lip"] },
    { theme: "Emotions", words: ["joy","fear","calm","mad","sad","glee","pride","shy","envy","hope"] },
    { theme: "Weather Words", words: ["fog","sun","rain","snow","wind","hail","mist","storm","frost","sleet","cloud"] },
    { theme: "Zoo Animals", words: ["lion","bear","wolf","zebra","tiger","panda","camel","koala","sloth","otter","hippo"] },
    { theme: "Insects", words: ["ant","bee","fly","gnat","moth","wasp","tick","flea","aphid","roach"] },
    { theme: "Birds", words: ["owl","hen","jay","crow","dove","duck","swan","robin","eagle","heron","raven","stork","quail"] },
    { theme: "Trees", words: ["elm","oak","fir","pine","palm","cedar","maple","birch","alder","aspen"] },
    { theme: "Flowers", words: ["rose","lily","iris","tulip","daisy","aster","lotus","poppy","phlox","pansy"] },
    { theme: "Shapes", words: ["box","star","oval","cube","cone","ring","disc","heart","arc","dot"] },
    { theme: "Gems And Stones", words: ["opal","ruby","jade","onyx","topaz","agate","pearl","amber","flint","slate"] },
    { theme: "Spices", words: ["mint","sage","dill","cumin","basil","clove","thyme","anise","mace","salt"] },
    { theme: "Drinks", words: ["milk","soda","cola","juice","water","cider","mocha","latte","punch","shake"] },
    { theme: "Desserts", words: ["cake","pie","tart","candy","fudge","donut","scone","jelly","cream","cocoa"] },
    { theme: "Clothing Items", words: ["hat","cap","tie","coat","vest","robe","sock","boot","shirt","pants","skirt","scarf","glove"] },
    { theme: "Furniture", words: ["bed","sofa","desk","lamp","sink","shelf","stool","couch","chair","table"] },
    { theme: "Tools", words: ["axe","saw","drill","plane","level","screw","clamp","file","vice","rake"] },
    { theme: "Board And Card Games", words: ["chess","sorry","risk","life","clue","snap","uno","ludo","war","spit"] },
    { theme: "Musical Instruments", words: ["drum","harp","horn","flute","banjo","viola","organ","piano","oboe","lute"] },
    { theme: "Toys", words: ["doll","kite","yoyo","top","robot","drone","bear","kazoo","dice","ball"] },
    { theme: "Bathroom Items", words: ["soap","comb","towel","brush","razor","sink","tub","drain","scale","robe"] },
    { theme: "Office Supplies", words: ["pen","clip","tape","stamp","paper","ruler","glue","desk","file","pin"] },
    { theme: "Camping Gear", words: ["tent","rope","torch","stove","knife","flask","tarp","map","lamp","axe"] },
    { theme: "Beach Items", words: ["sand","wave","surf","shell","towel","float","crab","kite","pail","raft"] },
    { theme: "Winter Items", words: ["snow","coat","boot","scarf","sled","ice","frost","skis","cocoa","mitt"] },
    { theme: "Family Members", words: ["mom","dad","son","aunt","uncle","niece","wife","papa","nana","gran"] },
    { theme: "Professions", words: ["cook","maid","monk","judge","nurse","pilot","actor","chef","coach","clerk"] },
    { theme: "Vehicles", words: ["car","van","cab","bus","jeep","taxi","truck","train","tram","sedan"] },
    { theme: "Boats", words: ["raft","ship","boat","canoe","kayak","yacht","barge","ferry","sloop","skiff"] },
    { theme: "Music Genres", words: ["jazz","rock","funk","folk","punk","blues","disco","metal","house","swing"] },
    { theme: "Fast Food Items", words: ["fries","pizza","taco","wrap","chips","shake","combo","meal","soda","melt"] },
    { theme: "Candy", words: ["mint","gum","taffy","fudge","gummy","lolly","chews","bar","nuts","drop"] },
    { theme: "Grains", words: ["rice","oats","corn","wheat","grain","bran","rye","maize","flour","germ"] },
    { theme: "Cheese Types", words: ["brie","feta","gouda","swiss","edam","curd","jack","colby","cream","blue"] },
    { theme: "Nuts And Seeds", words: ["nut","pecan","chia","hemp","flax","seed","bean","pod","husk","shell"] },
    { theme: "Seafood", words: ["crab","clam","cod","eel","squid","prawn","tuna","bass","sole","carp"] },
    { theme: "Reptiles", words: ["snake","gecko","skink","viper","cobra","croc","adder","boa","asp","gator","mamba"] },
    { theme: "Farm Tools", words: ["rake","hoe","plow","spade","fork","yoke","cart","pail","sack","silo"] },
    { theme: "Garden Items", words: ["hoe","rake","seed","soil","pot","vine","stem","leaf","bloom","petal"] },
    { theme: "Chess And Card Terms", words: ["king","pawn","rook","ace","suit","deck","joker","queen","trick","trump"] },
    { theme: "Music Terms", words: ["beat","bass","alto","tempo","chord","scale","pitch","verse","solo","duet"] },
    { theme: "Dances", words: ["jive","tango","waltz","polka","salsa","disco","swing","twist","samba","conga"] },
    { theme: "Building Materials", words: ["wood","brick","stone","glass","steel","clay","tile","sand","plank","brass"] },
    { theme: "Sea And Sky Words", words: ["star","moon","sun","tide","wave","reef","cave","cliff","dune","cove"] },
  ],

  medium: [
    { theme: "Dog Breeds", words: ["poodle","beagle","boxer","husky","collie","terrier","spaniel","bulldog","corgi","basset"] },
    { theme: "Greek Mythology", words: ["athena","hades","apollo","hermes","medusa","cronus","circe","midas","atlas","perseus","theseus"] },
    { theme: "US States", words: ["texas","idaho","maine","nevada","oregon","alaska","hawaii","kansas","georgia","arizona","florida","indiana","montana"] },
    { theme: "Musical Instruments", words: ["guitar","violin","trumpet","flute","piano","cello","bassoon","cymbal","maracas","ukulele"] },
    { theme: "Card Games", words: ["poker","bridge","rummy","hearts","euchre","canasta","spades","whist","bezique","pitch"] },
    { theme: "Board Games", words: ["chess","sorry","trouble","yahtzee","taboo","othello","mancala","jenga","connect","hangman"] },
    { theme: "Italian Foods", words: ["penne","rotini","ravioli","gnocchi","fusilli","lasagna","risotto","panini","gelato","pesto","salami"] },
    { theme: "Superheroes", words: ["batman","flash","storm","robin","cyclops","magneto","phoenix","electro","vulture","falcon"] },
    { theme: "World Cities", words: ["nairobi","lisbon","jakarta","ottawa","london","madrid","berlin","warsaw","dublin","vienna","athens","moscow"] },
    { theme: "Kitchen Appliances", words: ["toaster","blender","freezer","skillet","griddle","kettle","burner","grater","peeler","opener"] },
    { theme: "Furniture", words: ["dresser","cabinet","ottoman","armoire","hammock","bureau","vanity","daybed","cushion","curtain"] },
    { theme: "Clothing", words: ["sweater","jacket","blouse","sandals","sneaker","necktie","earring","legging","slipper","trouser"] },
    { theme: "Sports", words: ["boxing","hockey","tennis","soccer","rowing","diving","bowling","fencing","archery","cricket","karate","cycling","curling"] },
    { theme: "Occupations", words: ["doctor","lawyer","farmer","singer","writer","banker","dancer","teacher","painter","plumber","butcher","soldier"] },
    { theme: "Countries", words: ["mexico","canada","brazil","russia","poland","sweden","norway","turkey","vietnam","germany","belgium"] },
    { theme: "Mammals", words: ["rabbit","beaver","badger","weasel","possum","raccoon","leopard","giraffe","buffalo","dolphin","gorilla"] },
    { theme: "Birds", words: ["sparrow","pelican","penguin","falcon","parrot","ostrich","peacock","seagull","pigeon","vulture"] },
    { theme: "Insects", words: ["cricket","ladybug","firefly","termite","cicada","beetle","hornet","mantis","earwig","weevil"] },
    { theme: "Flowers", words: ["jasmine","petunia","begonia","dahlia","orchid","crocus","violet","zinnia","freesia","peony"] },
    { theme: "Trees", words: ["willow","walnut","cypress","redwood","hickory","juniper","spruce","poplar","banyan","conifer"] },
    { theme: "Gemstones", words: ["emerald","diamond","citrine","peridot","zircon","garnet","jasper","spinel","apatite","kunzite"] },
    { theme: "Metals", words: ["copper","silver","nickel","bronze","cobalt","mercury","uranium","brass","pewter","chrome"] },
    { theme: "Spices", words: ["oregano","paprika","saffron","fennel","nutmeg","ginger","mustard","anise","cumin","pepper"] },
    { theme: "Desserts", words: ["brownie","cupcake","pudding","sundae","custard","macaron","biscuit","cookie","waffle","parfait"] },
    { theme: "Drinks", words: ["whiskey","brandy","martini","mojito","sangria","eggnog","seltzer","spritz","cordial","punch"] },
    { theme: "Dances", words: ["foxtrot","shuffle","mambo","rumba","bolero","hustle","twerk","lambada","salsa","boogie"] },
    { theme: "Music Genres", words: ["reggae","techno","grunge","ambient","country","trance","gospel","ballad","fusion","ragtime"] },
    { theme: "Weather Phenomena", words: ["drizzle","thunder","tornado","cyclone","tsunami","monsoon","typhoon","rainbow","squall","breeze"] },
    { theme: "Constellations", words: ["orion","draco","cygnus","phoenix","dorado","hydra","indus","lupus","carina","norma"] },
    { theme: "Planets And Space", words: ["venus","earth","saturn","uranus","mercury","jupiter","neptune","pluto","comet","meteor","galaxy","nebula","rocket"] },
    { theme: "Body Parts", words: ["elbow","ankle","wrist","throat","spine","tongue","eyelid","eyebrow","forearm","stomach"] },
    { theme: "Professions", words: ["plumber","butcher","soldier","chemist","dentist","surgeon","curator","jeweler","tailor","florist"] },
    { theme: "Vehicles", words: ["scooter","bicycle","tractor","trailer","minivan","caravan","wagon","subway","trolley","hearse"] },
    { theme: "Boats", words: ["steamer","trawler","dinghy","gondola","clipper","tugboat","cruiser","kayak","yacht","barge"] },
    { theme: "Reptiles", words: ["iguana","lizard","python","monitor","caiman","gharial","mamba","cobra","gecko","adder"] },
    { theme: "Farm Equipment", words: ["tractor","combine","harvest","trailer","harrow","sprayer","feeder","baler","mower","seeder"] },
    { theme: "Sea Terms", words: ["current","seaweed","coastal","estuary","lagoon","harbor","shallow","coral","marina","jetty"] },
    { theme: "Cheese Types", words: ["cheddar","gruyere","ricotta","havarti","romano","paneer","burrata","stilton","queso","asiago"] },
    { theme: "Nuts And Seeds", words: ["almond","walnut","cashew","peanut","pumpkin","sesame","acorn","quinoa","lentil","legume"] },
    { theme: "Seafood", words: ["lobster","oyster","salmon","herring","halibut","scallop","mussel","octopus","anchovy","sardine"] },
    { theme: "Winter Sports", words: ["skiing","curling","bobsled","skating","hockey","slalom","mogul","igloo","parka","beanie"] },
    { theme: "Summer Sports", words: ["surfing","diving","rowing","sailing","cycling","archery","fencing","frisbee","paddle","tennis"] },
    { theme: "Yoga Poses", words: ["cobra","eagle","camel","bridge","locust","warrior","pigeon","dolphin","plank","chair"] },
    { theme: "Video Game Genres", words: ["puzzle","arcade","shooter","sandbox","racing","rhythm","stealth","horror","action","combat"] },
    { theme: "Building Types", words: ["cottage","mansion","chateau","cabin","castle","chapel","tower","palace","temple","bunker"] },
    { theme: "Musical Terms", words: ["melody","harmony","rhythm","cadence","vibrato","octave","chorus","bridge","refrain","timbre"] },
    { theme: "Weather And Climate", words: ["humid","arctic","desert","tundra","climate","drought","tornado","tropics","glacier","breeze"] },
    { theme: "School Subjects", words: ["science","history","english","biology","physics","algebra","drama","music","civics","reading"] },
    { theme: "Kitchen Utensils", words: ["spatula","ladle","tongs","grater","peeler","skewer","whisk","masher","funnel","opener"] },
    { theme: "Sky And Sunlight", words: ["rainbow","horizon","eclipse","sunrise","sunset","aurora","zenith","equinox","meteor","cosmos"] },
    { theme: "Types Of Bread", words: ["bagel","brioche","pretzel","challah","bannock","scone","muffin","biscuit","crumpet","matzo"] },
    { theme: "Types Of Tea", words: ["oolong","jasmine","rooibos","matcha","herbal","masala","ginger","sencha","puerh","assam"] },
    { theme: "Ocean Animals", words: ["dolphin","narwhal","urchin","mollusk","walrus","beluga","manatee","turtle","marlin","grouper"] },
    { theme: "Coffee And Cafe", words: ["latte","mocha","blend","roast","grinds","barista","creamer","saucer","thermos","kettle"] },
  ],

  hard: [
    { theme: "Chemical Elements", words: ["hydrogen","nitrogen","fluorine","chlorine","platinum","tungsten","selenium","strontium","potassium","manganese","titanium","calcium"] },
    { theme: "Shakespeare Plays And Characters", words: ["macbeth","othello","tempest","cymbeline","pericles","ophelia","cordelia","desdemona","cleopatra","prospero","caliban","falstaff"] },
    { theme: "World Capitals", words: ["nairobi","jakarta","canberra","budapest","singapore","helsinki","brussels","santiago","asuncion","kathmandu"] },
    { theme: "Constellations", words: ["pegasus","cepheus","hercules","aquarius","andromeda","capricorn","scorpius","columba","perseus","lacerta"] },
    { theme: "Programming Languages", words: ["assembly","haskell","fortran","clojure","graphql","verilog","crystal","solidity","angular","smalltalk"] },
    { theme: "Classical Composers", words: ["debussy","sibelius","paganini","beethoven","schubert","vivaldi","purcell","puccini","rossini","respighi"] },
    { theme: "Extinct Animals", words: ["mammoth","aurochs","thylacine","megalodon","glyptodon","archelon","smilodon","gastornis","pterosaur","titanoboa"] },
    { theme: "Renaissance Artists", words: ["raphael","donatello","bellini","giorgione","perugino","mantegna","correggio","veronese","carpaccio","bramante"] },
    { theme: "Mythical Creatures", words: ["griffin","basilisk","werewolf","minotaur","banshee","chimera","cerberus","pegasus","phoenix","mermaid"] },
    { theme: "Famous Scientists", words: ["einstein","galileo","faraday","pasteur","lavoisier","hawking","mendeleev","avogadro","boltzmann","linnaeus"] },
    { theme: "Orchestral Instruments", words: ["trombone","clarinet","bassoon","trumpet","cymbals","triangle","xylophone","saxophone","euphonium","clavinet"] },
    { theme: "Occupations", words: ["therapist","architect","paramedic","detective","professor","librarian","secretary","carpenter","mechanic","economist"] },
    { theme: "Countries", words: ["thailand","cambodia","portugal","slovakia","bulgaria","argentina","venezuela","australia","indonesia","guatemala"] },
    { theme: "African Countries", words: ["tanzania","botswana","zimbabwe","mauritius","cameroon","ethiopia","algeria","tunisia","senegal","nigeria"] },
    { theme: "Asian Countries", words: ["mongolia","pakistan","malaysia","myanmar","vietnam","bahrain","lebanon","cambodia","thailand","indonesia"] },
    { theme: "European Countries", words: ["portugal","bulgaria","slovakia","slovenia","croatia","hungary","ireland","ukraine","belgium","germany"] },
    { theme: "Greek Gods", words: ["poseidon","dionysus","aphrodite","demeter","artemis","hercules","hyperion","oceanus","asclepius","nemesis"] },
    { theme: "Roman Gods", words: ["jupiter","neptune","minerva","mercury","bacchus","quirinus","terminus","silvanus","vertumnus","vulcanus"] },
    { theme: "Geological Terms", words: ["mountain","volcano","plateau","sediment","limestone","obsidian","feldspar","graphite","magnetite","tectonic"] },
    { theme: "Ocean Zones", words: ["sunlight","twilight","midnight","abyssal","benthic","pelagic","littoral","neritic","bathyal","estuarine"] },
    { theme: "Space Terms", words: ["asteroid","satellite","telescope","supernova","wormhole","meteorite","cosmonaut","astronaut","parallax","aphelion"] },
    { theme: "Body Organs", words: ["stomach","pancreas","appendix","intestine","diaphragm","esophagus","bladder","thyroid","ventricle","clavicle"] },
    { theme: "Weather Phenomena", words: ["hurricane","blizzard","avalanche","lightning","whirlwind","heatwave","sandstorm","hailstorm","monsoon","cyclone"] },
    { theme: "Academic Subjects", words: ["chemistry","geometry","calculus","geography","economics","astronomy","sociology","genetics","geology","zoology"] },
    { theme: "Musical Terms", words: ["crescendo","staccato","vibrato","harmonic","dissonant","orchestra","symphony","concerto","ensemble","conductor"] },
    { theme: "Card Game Terms", words: ["solitaire","blackjack","canasta","cribbage","pinochle","baccarat","patience","klondike","freecell","pyramid"] },
    { theme: "Board Game Terms", words: ["monopoly","scrabble","checkers","dominoes","parcheesi","mancala","stratego","othello","yahtzee","sequence"] },
    { theme: "Insects", words: ["butterfly","dragonfly","centipede","millipede","ladybird","cockroach","stinkbug","lacewing","mosquito","termite"] },
    { theme: "Trees", words: ["eucalypt","mangrove","cypress","sycamore","chestnut","mahogany","jacaranda","rosewood","ironwood","dogwood"] },
    { theme: "Flowers", words: ["hibiscus","marigold","daffodil","camellia","lavender","carnation","gardenia","hyacinth","bluebell","buttercup"] },
    { theme: "Gemstones", words: ["moonstone","turquoise","amethyst","tanzanite","malachite","rhodonite","sapphire","diamond","emerald","peridot"] },
    { theme: "Metals And Alloys", words: ["chromium","palladium","beryllium","vanadium","cadmium","gunmetal","iridium","rhodium","niobium","tungsten"] },
    { theme: "Kitchen Gadgets", words: ["microwave","saucepan","casserole","spatula","colander","ramekin","skillet","griddle","cauldron","teakettle"] },
    { theme: "Herbs And Spices", words: ["cardamom","turmeric","rosemary","tarragon","marjoram","cinnamon","coriander","fenugreek","arrowroot","chervil"] },
    { theme: "Sports", words: ["baseball","football","softball","handball","badminton","athletics","taekwondo","triathlon","lacrosse","billiards"] },
    { theme: "Olympic Sports", words: ["swimming","curling","shooting","canoeing","climbing","cycling","marathon","decathlon","fencing","sailing"] },
    { theme: "Poker Terms", words: ["showdown","straight","bluffing","checking","raising","folding","betting","jackpot","wildcard","cardshark"] },
    { theme: "Weather And Seasons", words: ["monsoon","harvest","blossom","solstice","equinox","frostbite","sunburn","humidity","overcast","rainfall"] },
    { theme: "More Countries", words: ["colombia","honduras","paraguay","uruguay","ecuador","zimbabwe","tanzania","botswana","mauritius","cameroon"] },
    { theme: "More Musical Instruments", words: ["accordion","mandolin","dulcimer","bagpipes","ocarina","melodica","theremin","marimba","celesta","autoharp"] },
    { theme: "Body Systems", words: ["skeletal","muscular","digestive","nervous","endocrine","lymphatic","vascular","cardiac","cellular","arterial"] },
    { theme: "Famous Explorers", words: ["magellan","columbus","cousteau","pizarro","vespucci","mackenzie","cartier","champlain","coronado","stanley"] },
    { theme: "Art Movements", words: ["baroque","realism","futurism","modernism","mannerism","symbolism","fauvism","dadaism","collage","orphism"] },
    { theme: "Literary Genres", words: ["mystery","fantasy","thriller","romance","tragedy","folklore","dystopia","biography","allegory","narrative"] },
    { theme: "Vegetables", words: ["broccoli","zucchini","eggplant","cucumber","artichoke","asparagus","butternut","rutabaga","radicchio","kohlrabi"] },
    { theme: "Fruits", words: ["pineapple","blueberry","raspberry","cranberry","nectarine","persimmon","mandarin","starfruit","jackfruit","kumquat"] },
    { theme: "Sauces And Condiments", words: ["ketchup","mustard","sriracha","teriyaki","barbecue","marinara","guacamole","chutney","vinegar","tabasco"] },
    { theme: "Desserts", words: ["macaroon","meringue","tiramisu","baklava","shortcake","truffle","sherbet","popsicle","marzipan","streusel"] },
    { theme: "Beverages", words: ["lemonade","chocolate","smoothie","milkshake","espresso","americano","macchiato","affogato","cocktail","mocktail"] },
    { theme: "Board Game Play Terms", words: ["gameboard","scorecard","opponent","strategy","teammate","referee","timeout","penalty","victory","champion"] },
    { theme: "More Occupations", words: ["historian","physician","columnist","biologist","geologist","zoologist","economist","therapist","architect","violinist"] },
    { theme: "Natural Disasters", words: ["landslide","wildfire","flooding","drought","sinkhole","cyclone","tsunami","blizzard","eruption","twister"] },
    { theme: "Space Exploration", words: ["spaceship","spacesuit","moonwalk","touchdown","orbiting","reentry","liftoff","docking","gravity","capsule"] },
  ],
};
